pipeline {

  agent any
  
  stages {
    stage('Modify Config Flags') {
      steps {
        sh '''sed -i "s:set(GPU_DEFINITIONS CLUBB_GPU CUDA):set(GPU_DEFINITIONS CLUBB_GPU CUDA SILHS_MULTI_COL_RAND_DUPLICATE):g" cmake/toolchains/linux_x86_64_nvhpc.cmake''' // only edits GPU entry
        sh '''utilities/create_multi_col_params.py -n 6 -mode dup_tweak -mirror true'''
      }
    }
    stage('Compile GPU_ACC') {
      steps {
          sh ''' source /etc/profile.d/larson-group.sh
                 module load nvhpc netcdf-fortran
                 ./compile.py -gpu openacc'''
      }
    }
    stage('Run GPU_ACC') {
      steps {
        lock( "GPU_${env.NODE_NAME}" ) {
          sh '''ulimit -s 8388608
                run_scripts/run_scm_all.py -nproc 1 -debug 0 -params clubb_params_multi_col.in -max_iters 200 -override penta_solve_method=2,tridiag_solve_method=2,l_lh_straight_mc=.true.'''
        }
      }
    }
    stage('Run Check Script') {
      steps {
        sh '''python tests/check_mirrored_multi_col_output.py output'''
      }
    }
  }
  post {
    failure {
      script {
      if ( "${env.JOB_NAME}" == "clubb_nvhpc_gpu_column_mirror_test" )
        // This command handles the email on failure feature of the jenkins test. This line is the same on every jenkins test.
      	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
