pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        sh 'compile/compile.bash'
      }
    }
    stage('Run CLUBB\'s G Unit Tests') {
      steps {
        sh 'run_scripts/run_G_unit_tests.bash'
      }
    }
  }
  post {
    always {
      cleanWs(cleanWhenFailure: true, cleanWhenAborted: true, cleanWhenSuccess: true)
    }
    failure {
      emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
    }
  }
}
