pipeline {
  agent {
    node {
      label 'Mac'
    }

  }
  stages {
    stage('Compile') {
      steps {
        sh '''compile/compile.bash'''
      }
    }
    stage('Run Clubb') {
      steps {
        sh 'run_scripts/run_scm_all.bash --min-cases'
      }
    }
  }
  post {
    always {
       cleanWs(cleanWhenFailure: true, cleanWhenSuccess: true, cleanWhenUnstable: true)
    }
    failure {
       emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
    }
  }
}
