pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        // The source step is done to bring in all the needed intel path variables to run the rest of the commands
        sh '''source /etc/profile.d/larson-group.sh
              module load intel netcdf-fortran
              ./compile.py'''
      }
    }
    stage('Run') {
      steps {
        sh '''run_scripts/run_scm_all.py'''
      }
    }
  }
  post { 
    always {
      // Certain logical functions like IF statements or TRY-CATCH blocks can only operate while in a script{} block
      script {
      // This cleans out the test workspace so the next run has a fresh start
      // However this only occurs when the test is named clubb_ifort_build
      // This is to prevent the branch and copy tests from deleting thier workspaces so they are available for debugging
      if ( "${env.JOB_NAME}" == "clubb_ifort_build" )
      	cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenSuccess: true, cleanWhenUnstable: true)
      }
    }
    failure {
      script {
      if ( "${env.JOB_NAME}" == "clubb_ifort_build" )
        // This command handles the email on failure feature of the jenkins test. This line is the same on every jenkins test.
	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
