
%This is a modified version of the automated plot generation scripts done
%by Brian Griffin.
%The modifications were done by Brandon Nielsen with the intent of making
%it possible to generate plots of two sets of data on demand without using
%Messner.

function compare_plots_cases_driver( HOC_sim1, HOC_sim2, compare_LES, compare_best, compare_HOC, ...
					plot_arm_sim1, plot_arm_97_sim1, plot_atex_sim1, plot_bomex_sim1, ...
                                        plot_clex9_nov02_sim1, plot_clex9_oct14_sim1, plot_cloud_feedback_s6_sim1, ...
                                        plot_cloud_feedback_s11_sim1, plot_cloud_feedback_s12_sim1, plot_cobra_sim1, ...
					plot_dycoms2_rf01_sim1, plot_dycoms2_rf02_do_sim1, ...
					plot_dycoms2_rf02_ds_sim1, plot_dycoms2_rf02_nd_sim1, ...
					plot_dycoms2_rf02_so_sim1, plot_fire_sim1, plot_gabls2_sim1, plot_gabls3_sim1, ...
					plot_jun25_altocu_sim1, plot_lba_sim1, plot_mpace_a_sim1, plot_mpace_b_sim1, ...
                                        plot_nov11_altocu_sim1, plot_rico_sim1, plot_twp_ice_sim1, plot_wangara_sim1 , ...
					plot_arm_sim2, plot_arm_97_sim2, plot_atex_sim2, plot_bomex_sim2, ...
                                        plot_clex9_nov02_sim2, plot_clex9_oct14_sim2, plot_cloud_feedback_s6_sim2, ...
                                        plot_cloud_feedback_s11_sim2, plot_cloud_feedback_s12_sim2, plot_cobra_sim2, ...
					plot_dycoms2_rf01_sim2, plot_dycoms2_rf02_do_sim2, ...
					plot_dycoms2_rf02_ds_sim2, plot_dycoms2_rf02_nd_sim2, ...
					plot_dycoms2_rf02_so_sim2, plot_fire_sim2, plot_gabls2_sim2, plot_gabls3_sim2, ...
					plot_jun25_altocu_sim2, plot_lba_sim2, plot_mpace_a_sim2, plot_mpace_b_sim2, ...
                                        plot_nov11_altocu_sim2, plot_rico_sim2, plot_twp_ice_sim2, plot_wangara_sim2 )

% Example call that plots one output of the arm case:                                    
%compare_plots_cases_driver( '../../output/', '../../output/', 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 )

% To run compare_plots_cases_driver manually, you need to cut and paste the above example call, with possibly 
% modified arguments, into the MATLAB command prompt.  Plots should appear in subdirectory output/eps
% of whatever directory compare_plots_cases_driver.m is in.

% The arguments to this function (compare_plots_cases_driver) are:
%
% HOC_sim1    = The directory path to the first set of CLUBB output files (.ctl and .dat files) to be plotted.
% HOC_sim2    = The directory path to the second set of CLUBB output files (.ctl and .dat files) to be plotted.
% compare_LES:  Set to 1 to overplot LES benchmark results; else set to 0. (Set to 0 if you're outside larsongroup.)
% compare_best: Set to 1 to overplot some prior CLUBB benchmarks; else 0. (Set to 0 if you're outside larsongroup.)
% compare_HOC:  Set to 1 to overplot some other prior CLUBB benchmarks; else 0. (Set to 0 if you're outside larsongroup.)
% plot_arm_sim1:   1 if you want to plot a line from the arm case; 0 if not.
% plot_arm97_sim1: 1 if you want to plot a line from the arm97 case; 0 if not.
% ...  for all other cases
% plot_arm_sim2:   1 if you want to overplot a second line from the arm case; 0 if not.
% plot_arm97_sim2: 1 if you want to overplot a second line from the arm97 case; 0 if not.
% ... for all other cases.
%
% E.g., if plot_arm_sim1 = 1, then compare_plots_cases_driver will look in directory HOC_sim1 for 
%   CLUBB output files that begin with "arm_" and plot the data; if plot_arm_sim2 = 1, then 
%   compare_plots_cases_driver will look in HOC_sim2 for "arm_" files and overplot that data.
%   If, additionally, plot_arm97_sim1 = 1, then compare_plot_cases_driver will create an additional
%   set of plots from arm97 output that it finds in directory HOC_sim1.  

% ################# TO-DO #################
% Make it possible to turn plots on and off
% Fix how cmp_all works, even in test trim it is worthless junk (ex. does not work when 0) (Fixed July 31, 2007)
% Ensure names are meteorologist friendly

% Function arguments description for the call to compare_plots_cases below:
%
% 1st entry:   Case name.
% 2nd entry:   First time of variable comparison (in minutes since the
%              beginning of the run).
% 3rd entry:   Last time of variable comparison (in minutes since the
%              beginning of the run).
% 4th entry:   The height of the bottom of the output graphs for each case.
% 5th entry:   The height of the top of the output graphs for each case.
% 6th entry:   The directory path that contains the LES files for
%              comparison. (omit the '/' at the very end.)
% 7th entry:   The directory path that contains the HOC "Chris Golaz
%              'best-ever'" files for comparison. (omit the '/' at the very
%              end.)
% 8th entry:   The directory path that contains the HOC December 17, 2005
%              files for comparison. (omit the '/' at the very end.)
% 9th entry:   The directory path that contains the HOC previous files
%              (from the prior CVS commitment) for comparison. (omit the
%              '/' at the very end.)
% 10th entry:  The directory path that contains the HOC current files (from 
%              the latest CVS commitment) for comparison. (omit the '/' at
%              the very end.)
% 11th entry:  LES file for comparison:  1 = true; 0 = false.
% 12th entry:  LES being using for comparison (supports coamps and rams).
% 13th entry:  Chris Golaz "best-ever" HOC file for comparison:  1 = true;
%                                                                0 = false.
% 14th entry:  December 17, 2005 HOC file for comparison:  1 = true;
%                                                         0 = false.
% 15th entry:  Previous CVS HOC file for comparison:  1 = true; 
%                                                    0 = false.
% 16th entry:  Current HOC file for comparison:  1 = true; 0 = false.

%Lets test some things
%Script runs when variables are explicitly defined (obviously...)
%'Hard assigning variables:'
%HOC_sim1 = 'HOC_current'
%HOC_sim2 = 'HOC_previous'
%compare_all = 0

%Determine if HOC_sim2 exists (should be plotted)
compare_sim2 = 1

if HOC_sim2 == 0
	compare_sim2 = 0
end;	

%Display the variables to potentially see what is wrong
'Variables set as follows:'
HOC_sim1
HOC_sim2
compare_sim2
compare_LES
compare_best
compare_HOC

if plot_arm_sim1 == 1
	if plot_arm_sim2 == 0
         	compare_plots_cases( 'arm', 481, 540, 0.0, 3500.0, ...
                              'LES_files', 'Chris_Golaz_best_ever', ...
                              'HOC_20051217', HOC_sim1, HOC_sim2, ...
                              compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
			      0 );
	elseif plot_arm_sim2 == 1
         	compare_plots_cases( 'arm', 481, 540, 0.0, 3500.0, ...
                              'LES_files', 'Chris_Golaz_best_ever', ...
                              'HOC_20051217', HOC_sim1, HOC_sim2, ...
                              compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
			      compare_sim2 );		
	end;
elseif plot_arm_sim1 == 0
	if plot_arm_sim2 == 0
         	'No sim data available for Arm, not plotting Arm.';
	elseif plot_arm_sim2 == 1
         	compare_plots_cases( 'arm', 481, 540, 0.0, 3500.0, ...
                              'LES_files', 'Chris_Golaz_best_ever', ...
                              'HOC_20051217', HOC_sim1, HOC_sim2, ...
                              compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
			      compare_sim2 );		
	end;
end;

if plot_arm_97_sim1 == 1
	if plot_arm_97_sim2 == 0
         	compare_plots_cases( 'arm_97', 4321, 5760, 0.0, 18000.0, ...
                              '', '', ...
                              '', HOC_sim1, HOC_sim2, ...
                              0, 'coamps', 0, 0, 1, ...
			      0 );
	elseif plot_arm_97_sim2 == 1
         	compare_plots_cases( 'arm_97', 4321, 5760, 0.0, 18000.0, ...
                              '', '', ...
                              '', HOC_sim1, HOC_sim2, ...
                              0, 'coamps', 0, 0, 1, ...
			      compare_sim2 );		
	end;
elseif plot_arm_97_sim1 == 0
	if plot_arm_97_sim2 == 0
         	'No sim data available for Arm_97, not plotting Arm_97.';
	elseif plot_arm_97_sim2 == 1
         	compare_plots_cases( 'arm_97', 4321, 5760, 0.0, 18000.0, ...
                              '', '', ...
                              '', HOC_sim1, HOC_sim2, ...
                              0, 'coamps', 0, 0, 0, ...
			      compare_sim2 );		
	end;
end;

if plot_atex_sim1 == 1
	if plot_atex_sim2 == 0
         	compare_plots_cases( 'atex', 421, 480, 0.0, 2500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_atex_sim2 == 1
         	compare_plots_cases( 'atex', 421, 480, 0.0, 2500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_atex_sim1 == 0
	if plot_atex_sim2 == 0
         	'No sim data available for Atex, not plotting Atex.';
	elseif plot_atex_sim2 == 1
         	compare_plots_cases( 'atex', 421, 480, 0.0, 2500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;

end;

if plot_bomex_sim1 == 1
	if plot_bomex_sim2 == 0
         	compare_plots_cases( 'bomex', 181, 360, 0.0, 2500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_bomex_sim2 == 1
         	compare_plots_cases( 'bomex', 181, 360, 0.0, 2500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_bomex_sim1 == 0
	if plot_bomex_sim2 == 0
         	'No sim data available for Bomex, not plotting Bomex.';
	elseif plot_bomex_sim2 == 1
         	compare_plots_cases( 'bomex', 181, 360, 0.0, 2500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;

end;

if plot_clex9_nov02_sim1 == 1
	if plot_clex9_nov02_sim2 == 0
         	compare_plots_cases( 'clex9_nov02', 91, 150, 3072.0, 6072.0, ...
					'LES_files', '', ...
					'', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_clex9_nov02_sim2 == 1
         	compare_plots_cases( 'clex9_nov02', 91, 150, 3072.0, 6072.0, ...
					'LES_files', '', ...
					'', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_clex9_nov02_sim1 == 0
	if plot_clex9_nov02_sim2 == 0
         	'No sim data available for CLEX-9: Nov.02, no plotting CLEX-9: Nov.02.';
	elseif plot_clex9_nov02_sim2 == 1
         	compare_plots_cases( 'clex9_nov02', 91, 150, 3072.0, 6072.0, ...
					'LES_files', '', ...
					'', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_clex9_oct14_sim1 == 1
	if plot_clex9_oct14_sim2 == 0
         	compare_plots_cases( 'clex9_oct14', 91, 150, 2188.0, 6688.0, ...
					'LES_files', '', ...
					'', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_clex9_oct14_sim2 == 1
         	compare_plots_cases( 'clex9_oct14', 91, 150, 2188.0, 6688.0, ...
					'LES_files', '', ...
					'', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_clex9_oct14_sim1 == 0
	if plot_clex9_oct14_sim2 == 0
         	'No sim data available for CLEX-9: Oct.14, no plotting CLEX-9: Oct.14.';
	elseif plot_clex9_oct14_sim2 == 1
         	compare_plots_cases( 'clex9_oct14', 91, 150, 2188.0, 6688.0, ...
					'LES_files', '', ...
					'', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_cloud_feedback_s6_sim1 == 1
	if plot_cloud_feedback_s6_sim2 == 0
        	 compare_plots_cases( 'cloud_feedback_s6', 41760, 43200, 0.0, 10000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_cloud_feedback_s6_sim2 == 1
        	 compare_plots_cases( 'cloud_feedback_s6', 41760, 43200, 0.0, 10000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_cloud_feedback_s6_sim1 == 0
	if plot_cloud_feedback_s6_sim2 == 0
        	 'No sim data available for Cloud Feedback S6, not plotting Cloud Feedback S6.';
	elseif plot_cloud_feedback_s6_sim2 == 1
        	 compare_plots_cases( 'cloud_feedback_s12',41760, 43200, 0.0, 10000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_cloud_feedback_s11_sim1 == 1
	if plot_cloud_feedback_s11_sim2 == 0
        	 compare_plots_cases( 'cloud_feedback_s11', 41760, 43200, 0.0, 10000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_cloud_feedback_s11_sim2 == 1
        	 compare_plots_cases( 'cloud_feedback_s11', 41760, 43200, 0.0, 10000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_cloud_feedback_s11_sim1 == 0
	if plot_cloud_feedback_s11_sim2 == 0
        	 'No sim data available for Cloud Feedback S11, not plotting Cloud Feedback S11.';
	elseif plot_cloud_feedback_s11_sim2 == 1
        	 compare_plots_cases( 'cloud_feedback_s11', 41760, 43200, 0.0, 10000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_cloud_feedback_s12_sim1 == 1
	if plot_cloud_feedback_s12_sim2 == 0
        	 compare_plots_cases( 'cloud_feedback_s12', 41760, 43200, 0.0, 10000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_cloud_feedback_s12_sim2 == 1
        	 compare_plots_cases( 'cloud_feedback_s12',41760, 43200, 0.0, 10000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_cloud_feedback_s12_sim1 == 0
	if plot_cloud_feedback_s12_sim2 == 0
        	 'No sim data available for Cloud Feedback S12, not plotting Cloud Feedback S12.';
	elseif plot_cloud_feedback_s12_sim2 == 1
        	 compare_plots_cases( 'cloud_feedback_s12', 41760, 43200, 0.0, 10000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_cobra_sim1 == 1
	if plot_cobra_sim2 == 0
         	compare_plots_cases( 'cobra', 241, 300, 0.0, 3500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', 0, 0, 1, ...
					0 );
	elseif plot_cobra_sim2 == 1
         	compare_plots_cases( 'cobra', 241, 300, 0.0, 3500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_cobra_sim1 == 0
	if plot_cobra_sim2 == 0
         	'No sim data available for Cobra, no plotting Cobra.';
	elseif plot_cobra_sim2 == 1
         	compare_plots_cases( 'cobra', 241, 300, 0.0, 3500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_dycoms2_rf01_sim1 == 1
	if plot_dycoms2_rf01_sim2 == 0
         	compare_plots_cases( 'dycoms2_rf01', 181, 240, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_dycoms2_rf01_sim2 == 1
         	compare_plots_cases( 'dycoms2_rf01', 181, 240, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_dycoms2_rf01_sim1 == 0
	if plot_dycoms2_rf01_sim2 == 0
         	'No sim data available for Dycoms2_RF01, not plotting Dycoms2_RF01.';
	elseif plot_dycoms2_rf01_sim2 == 1
         	compare_plots_cases( 'dycoms2_rf01', 181, 240, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

if plot_dycoms2_rf02_do_sim1 == 1
	if plot_dycoms2_rf02_do_sim2 == 0
        	 compare_plots_cases( 'dycoms2_rf02_do', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );

	elseif plot_dycoms2_rf02_do_sim2
        	 compare_plots_cases( 'dycoms2_rf02_do', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_dycoms2_rf02_do_sim1 == 0
	if plot_dycoms2_rf02_do_sim2 == 0
        	 'No sim data available for Dycoms2_RF02_DO, not plotting Dycons2_RF02_DO.';
	else plot_dycoms2_rf02_do_sim2 == 1
        	 compare_plots_cases( 'dycoms2_rf02_do', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

if plot_dycoms2_rf02_ds_sim1 == 1
	if plot_dycoms2_rf02_ds_sim2 == 0
         	compare_plots_cases( 'dycoms2_rf02_ds', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_dycoms2_rf02_ds_sim2 == 1
         	compare_plots_cases( 'dycoms2_rf02_ds', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_dycoms2_rf02_ds_sim1 == 0
	if plot_dycoms2_rf02_ds_sim2 == 0
         	'No sim data available for Dycoms_RF02_DS, not plotting Dycoms_RF02_DS.';
	elseif plot_dycoms2_rf02_ds_sim2 == 1
         	compare_plots_cases( 'dycoms2_rf02_ds', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

if plot_dycoms2_rf02_nd_sim1 == 1
	if plot_dycoms2_rf02_nd_sim2 == 0
         	compare_plots_cases( 'dycoms2_rf02_nd', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_dycoms2_rf02_nd_sim2 == 1
         	compare_plots_cases( 'dycoms2_rf02_nd', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_dycoms2_rf02_nd_sim1 == 0
	if plot_dycoms2_rf02_nd_sim2 == 0
         	'No sim data available for Dycoms2_RF02_ND, not plotting Dycoms2_RF02_ND.';
	elseif plot_dycoms2_rf02_nd_sim2 == 1
         	compare_plots_cases( 'dycoms2_rf02_nd', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;

end;

if plot_dycoms2_rf02_so_sim1 == 1
	if plot_dycoms2_rf02_so_sim2 == 0
        	 compare_plots_cases( 'dycoms2_rf02_so', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_dycoms2_rf02_so_sim2 == 1
        	 compare_plots_cases( 'dycoms2_rf02_so', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_dycoms2_rf02_so_sim1 == 0
	if plot_dycoms2_rf02_so_sim2 == 0
        	 'No sim data available for Dycoms_RF02_SO, not plotting Dycoms_RF02_SO.';
	elseif plot_dycoms2_rf02_so_sim2 == 1
        	 compare_plots_cases( 'dycoms2_rf02_so', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

if plot_fire_sim1 == 1
	if plot_fire_sim2 == 0
        	 compare_plots_cases( 'fire', 61, 120, 0.0, 1000.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_fire_sim2 == 1
        	 compare_plots_cases( 'fire', 61, 120, 0.0, 1000.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_fire_sim1 == 0
	if plot_fire_sim2 == 0
        	 'No sim data available for Fire, not plotting Fire.';
	elseif plot_fire_sim2 == 1
        	 compare_plots_cases( 'fire', 61, 120, 0.0, 1000.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

if plot_gabls2_sim1 == 1
	if plot_gabls2_sim2 == 0
         	compare_plots_cases( 'gabls2', 2101, 2160, 0.0, 2500.0, ...
			'LES_files', 'Chris_Golaz_best_ever', ...
			'HOC_20051217', HOC_sim1, HOC_sim2, ...
			compare_LES, 'coamps', 0, 0, 1, ...
			0 );
	elseif plot_gabls2_sim2 == 1
         	compare_plots_cases( 'gabls2', 2101, 2160, 0.0, 2500.0, ...
			'LES_files', 'Chris_Golaz_best_ever', ...
			'HOC_20051217', HOC_sim1, HOC_sim2, ...
			compare_LES, 'coamps', 0, 0, 1, ...
			compare_sim2 );
	end;
elseif plot_gabls2_sim1 == 0
	if plot_gabls2_sim2 == 0
         	'No sim data available for Gabls2, not plotting Gabls2.';
	elseif plot_gabls2_sim2 == 1
         	compare_plots_cases( 'gabls2', 2101, 2160, 0.0, 2500.0, ...
			'LES_files', 'Chris_Golaz_best_ever', ...
			'HOC_20051217', HOC_sim1, HOC_sim2, ...
			compare_LES, 'coamps', 0, 0, 0, ...
			compare_sim2 );
	end;
end;
if plot_gabls3_sim1 == 1
	if plot_gabls3_sim2 == 0
         	compare_plots_cases( 'gabls3', 1080, 1200, 0.0, 4970.0, ...
                              '', '', ...
                              '', HOC_sim1, HOC_sim2, ...
                              0, 'coamps', 0, 0, 1, ...
			      0 );
	elseif plot_gabls3_sim2 == 1
         	compare_plots_cases( 'gabls3', 1080, 1200, 0.0, 4970.0, ...
                              '', '', ...
                              '', HOC_sim1, HOC_sim2, ...
                              0, 'coamps', 0, 0, 1, ...
			      compare_sim2 );		
	end;
elseif plot_gabls3_sim1 == 0
	if plot_gabls3_sim2 == 0
         	'No gabls3 available for GABLS3, not plotting GABLS3.';
	elseif plot_arm_97_sim2 == 1
         	compare_plots_cases( 'gabls3', 72, 144, 0.0, 4970.0, ...
                              '', '', ...
                              '', HOC_sim1, HOC_sim2, ...
                              0, 'coamps', 0, 0, 0, ...
			      compare_sim2 );		
	end;
end;



if plot_jun25_altocu_sim1 == 1
	if plot_jun25_altocu_sim2 == 0
         	compare_plots_cases( 'jun25_altocu', 61, 120, 4808.0, 7308.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_jun25_altocu_sim2 == 1
         	compare_plots_cases( 'jun25_altocu', 61, 120, 4808.0, 7308.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_jun25_altocu_sim1 == 0
	if plot_jun25_altocu_sim2 == 0
         	'No sim data available for Jun25_altocu, not plotting Jun25_altocu.';
	elseif plot_jun25_altocu_sim2 == 1
         	compare_plots_cases( 'jun25_altocu', 61, 120, 4808.0, 7308.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_lba_sim1 == 1
	if plot_lba_sim2 == 0
         	compare_plots_cases( 'lba', 301.0, 360.0, 0.0, 16000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_lba_sim2 == 1
         	compare_plots_cases( 'lba', 301.0, 360.0, 0.0, 16000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_lba_sim1 == 0
	if plot_lba_sim2 == 0
         	'No sim data available for LBA, not LBA';
	elseif plot_lba_sim2 == 1
         	compare_plots_cases( 'lba', 301.0, 360.0, 0.0, 16000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_mpace_a_sim1 == 1
	if  plot_mpace_a_sim2 == 0
        	 compare_plots_cases( 'mpace_a', 4140, 4320, 0.0, 10000.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', 0, 0, 1, ...
					0 );
	elseif plot_mpace_a_sim2 == 1
        	 compare_plots_cases( 'mpace_a', 4140, 4320, 0.0, 10000.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_mpace_a_sim1 == 0
	if  plot_mpace_a_sim2 == 0
        	 'No sim data available for Mpace_a, not plotting Mpace_a';
	elseif plot_mpace_a_sim2 == 1
        	 compare_plots_cases( 'mpace_a', 4140, 4320, 0.0, 10000.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_mpace_b_sim1 == 1
	if  plot_mpace_b_sim2 == 0
        	 compare_plots_cases( 'mpace_b', 541, 720, 0.0, 2750.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_mpace_b_sim2 == 1
        	 compare_plots_cases( 'mpace_b', 541, 720, 0.0, 2750.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_mpace_b_sim1 == 0
	if  plot_mpace_b_sim2 == 0
        	 'No sim data available for Mpace_b, not plotting Mpace_b';
	elseif plot_mpace_b_sim2 == 1
        	 compare_plots_cases( 'mpace_b', 541, 720, 0.0, 2750.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_nov11_altocu_sim1 == 1
	if plot_nov11_altocu_sim2 == 0
         	compare_plots_cases( 'nov11_altocu', 61, 120, 4150.0, 6150.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_nov11_altocu_sim2 == 1
         	compare_plots_cases( 'nov11_altocu', 61, 120, 4150.0, 6150.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_nov11_altocu_sim1 == 0
	if plot_nov11_altocu_sim2 == 0
         	'No sim data available for Nov11_Altocu, not plotting Nov11_Altocu.';
	elseif plot_nov11_altocu_sim2 == 1
         	compare_plots_cases( 'nov11_altocu', 61, 120, 4150.0, 6150.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

if plot_rico_sim1 == 1
	if plot_rico_sim2 == 0
        	 compare_plots_cases( 'rico', 1261, 1440, 0.0, 3500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_rico_sim2 == 1
        	 compare_plots_cases( 'rico', 1261, 1440, 0.0, 3500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_rico_sim1 == 0
	if plot_rico_sim2 == 0
        	 'No sim data available for Rico, not plotting Rico.';
	elseif plot_rico_sim2 == 1
        	 compare_plots_cases( 'rico', 1261, 1440, 0.0, 3500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_twp_ice_sim1 == 1
	if plot_twp_ice_sim2 == 0
        	 compare_plots_cases( 'twp_ice', 37260, 38700, 0.0, 16000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_twp_ice_sim2 == 1
        	 compare_plots_cases( 'twp_ice', 37260, 38700, 0.0, 16000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_twp_ice_sim1 == 0
	if plot_twp_ice_sim2 == 0
        	 'No sim data available for TWP_ICE, not plotting TWP_ICE.';
	elseif plot_twp_ice_sim2 == 1
        	 compare_plots_cases( 'twp_ice', 37260, 38700, 0.0, 16000.0, ...
					'', '', ...
					'', HOC_sim1, HOC_sim2, ...
					0, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_wangara_sim1 == 1
	if plot_wangara_sim2 == 0
         	compare_plots_cases( 'wangara', 181, 240, 0.0, 1900.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'rams', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_wangara_sim2 == 1
         	compare_plots_cases( 'wangara', 181, 240, 0.0, 1900.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'rams', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_wangara_sim1 == 0
	if plot_wangara_sim2 == 0
         	'No sim data available for Wangara, not plotting Wangara.';
	elseif plot_wangara_sim2 == 1
         	compare_plots_cases( 'wangara', 181, 240, 0.0, 1900.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'rams', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

'Plot generation complete!'
