"""Check reusable JAX loss sessions against native loss-driver contracts.

The repeated-call and changed-parameter scenarios follow
src/clubb_loss_driver_test.F90 (run_manual_loss_bfb_test,
run_tweaked_parameter_test and run_reinitialize_loss_bfb_test). Scoring and
successive-window behavior come from src/clubb_loss_driver.F90
(clubb_get_loss_for_params, prepare_loss_request_for_scoring and
calculate_field_loss).

A ten-step BOMEX fixture scores two fields in two windows against synthetic
benchmark profiles, with four parameter columns and runtime width two. Checks
cover exact repeated results, refreshed derived state, benchmark boundaries,
invalid-candidate isolation and lifecycle/configuration errors. Fixed-shape
short batches and compilation-cache reuse are additional JAX assertions.

The numerical oracle runs the native loss executable and compares all five
reported metrics at its text-output precision. Build
install/latest/clubb_standalone_loss or set CLUBB_TEST_LOSS_EXE to that executable. Temporary
namelists and benchmark files are generated by the fixture; no F2PY is used.
"""
import importlib.abc
import os
from pathlib import Path
import subprocess
import sys

import jax
import jax.numpy as jnp
import numpy as np
from netCDF4 import Dataset
import pytest

from clubb_jax.src import clubb_loss_driver as loss
from clubb_jax.src.CLUBB_core.advance_clubb_core_module import advance_clubb_core
from clubb_jax.src.CLUBB_core.parameters_tunable import PNAME_IDX, init_clubb_params
from clubb_jax.src.CLUBB_core.stats_netcdf import StatsWriter
from clubb_jax.src.CLUBB_core.err_info import ErrInfo
from utilities.create_case_namelist import (
    create_case_namelist_file, prune_clubb_stats_namelist, set_stats_string, set_stats_value,
)

ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture(scope='module')
def prepared_loss(tmp_path_factory):
    from clubb_jax.src.CLUBB_core import error_code
    original_debug_level = error_code._debug_level
    tmp_path = tmp_path_factory.mktemp('jax_loss')
    jax.clear_caches()
    benchmark = tmp_path / 'truth.nc'
    times = np.arange(0., 601., 60.)
    z = np.arange(0., 6001., 20.)
    with Dataset(benchmark, 'w', format='NETCDF3_64BIT_OFFSET') as ds:
        for name, values in [('time', times), ('z', z), ('y', [1.]), ('x', [1.])]:
            ds.createDimension(name, len(values))
            ds.createVariable(name, 'f8', (name,))[:] = values
        ds['time'].units = 'seconds since 1969-06-22 00:00:00'
        ds['z'].units = 'm'
        ds.createVariable('thlm', 'f8', ('time', 'z', 'y', 'x'))[:] = (
            300. + z[None, :] * .004 + times[:, None] * .00001)[:, :, None, None]
        ds.createVariable('wp2', 'f8', ('time', 'z', 'y', 'x'))[:] = (
            .05 + z[None, :] * .00004 + times[:, None] * .000005)[:, :, None, None]
        ds['thlm'].units = 'K'
        ds['wp2'].units = 'm^2/s^2'
    path = create_case_namelist_file(
        'bomex', tmp_path, stats=str(ROOT / 'input/stats/standard_stats.in'),
        multicol='4', batch_size=2, debug='-1', max_iters=10,
    )
    text = prune_clubb_stats_namelist(path.read_text(), ['thlm', 'wp2'])
    text = set_stats_string(text, 'stats_output_filename', '')
    for name, value in dict(stats_tstart=0, stats_tend=600, stats_tout=300, stats_tsamp=60).items():
        text = set_stats_value(text, name, str(value))
    text += f'''\n&tuner_loss_nl
 les_stats_file="{benchmark}"
 clubb_var_names(1)="thlm"
 clubb_var_names(2)="wp2"
 benchmark_var_name(1)="thlm"
 benchmark_var_name(2)="wp2"
 altitude_comparison_range=20,2940
 time_average_range=0,600
 num_time_windows=2
/\n'''
    path.write_text(text)
    names, params = loss.init_clubb_loss(str(path), True)
    yield path, names, params
    loss.finalize_clubb_loss()
    error_code._debug_level = original_debug_level
    jax.clear_caches()


def test_repeated_batches_reset_derived_state_and_reuse_jit(prepared_loss):
    path, names, params = prepared_loss
    assert names == ['thlm', 'wp2']
    assert params.shape == (4, 102)
    assert loss.get_loss_time_window_count() == 2
    assert loss.active_request.state['stats_writer']._ncid is None
    baseline = loss.clubb_get_loss_for_params(params)
    cache_size = advance_clubb_core._cache_size()
    changed = params.at[:, PNAME_IDX['C8']].set(.65)
    changed = changed.at[:, PNAME_IDX['nu1']].set(1.5)
    changed = changed.at[:, PNAME_IDX['lmin_coef']].set(.6)
    changed = changed.at[:, PNAME_IDX['Skw_max_mag']].set(8.)
    result = loss.clubb_get_loss_for_params(changed)
    assert advance_clubb_core._cache_size() == cache_size
    assert any(np.any(np.asarray(a) != np.asarray(b)) for a, b in zip(baseline, result))
    assert float(loss.active_request.state['lmin']) == 24.
    np.testing.assert_allclose(loss.active_request.state['nu_vert_res_dep'].nu1, 1.5)
    again = loss.clubb_get_loss_for_params(params)
    for first, repeated in zip(baseline, again):
        assert first.shape == (2, 2, 4)
        np.testing.assert_array_equal(first, repeated)
        assert np.isfinite(first).all()
    # Odd and smaller candidate counts use the same compiled runtime shape.
    short = loss.clubb_get_loss_for_params(params[:3])
    single = loss.clubb_get_loss_for_params(params[:1])
    for full, partial, one in zip(baseline, short, single):
        np.testing.assert_array_equal(full[..., :3], partial)
        np.testing.assert_array_equal(full[..., :1], one)
    assert advance_clubb_core._cache_size() == cache_size
    assert not list(path.parent.glob('*stats.nc'))


@pytest.mark.parametrize('bad_value', [np.nan, np.inf, -1.])
def test_invalid_candidate_preserves_healthy_neighbor(prepared_loss, bad_value):
    _, _, params = prepared_loss
    healthy = loss.clubb_get_loss_for_params(params[:2])
    invalid = params[:2].at[0, PNAME_IDX['C8']].set(bad_value)
    result = loss.clubb_get_loss_for_params(invalid)
    for values, expected, penalty in zip(result, healthy, loss.set_invalid_field_metric_outputs()):
        np.testing.assert_array_equal(values[..., 1], expected[..., 1])
        np.testing.assert_array_equal(values[..., 0], penalty)
        assert np.isfinite(values).all()


def test_benchmark_windows_exclude_start_include_end(prepared_loss):
    # Linear profiles make interpolation exact; records at t=0/300 must not
    # contaminate the first/second averages respectively.
    field = loss.active_request.fields[0]
    state = loss.active_request.state
    grid = np.asarray(state['gr'].zt)[0, field.k_min:field.k_max + 1]
    expected = 300. + grid[None, :] * .004 + np.array([180., 480.])[:, None] * .00001
    np.testing.assert_allclose(field.truth_profile, expected, atol=1.e-12, rtol=0)


def test_loss_matches_fortran_executable(prepared_loss):
    executable = Path(os.environ.get(
        'CLUBB_TEST_LOSS_EXE', ROOT / 'install/latest/clubb_standalone_loss',
    )).resolve()
    assert executable.is_file(), (
        'Build the Fortran loss executable or set CLUBB_TEST_LOSS_EXE to its path'
    )
    path, names, params = prepared_loss
    oracle = subprocess.run([str(executable), str(path)], cwd=ROOT / 'run_scripts',
                            text=True, capture_output=True)
    assert oracle.returncode in (0, 6), oracle.stdout + oracle.stderr
    rows = [line.split() for line in oracle.stdout.splitlines()
            if line.split() and line.split()[0] in names and line.split()[1].startswith('window')]
    assert len(rows) == 4, oracle.stdout
    expected = np.array([[float(value) for value in row[2:-1]] for row in rows]).reshape(2, 2, 5, 4)
    result = np.stack(loss.clubb_get_loss_for_params(params), axis=2)
    # The executable's text table retains 8 digits after the decimal.
    np.testing.assert_allclose(result, expected, rtol=1.e-7, atol=2.e-8)


def test_loss_driver_runs_without_fortran(prepared_loss):
    class BlockFortran(importlib.abc.MetaPathFinder):
        def find_spec(self, fullname, path=None, target=None):
            if fullname == 'clubb_f2py' or fullname == 'clubb_python' or fullname.startswith('clubb_python.'):
                raise ImportError('Fortran runtime blocked')
    blocker = BlockFortran()
    sys.meta_path.insert(0, blocker)
    try:
        result = loss.clubb_get_loss_for_params(prepared_loss[2])
        assert np.isfinite(result[0]).all()
    finally:
        sys.meta_path.remove(blocker)


@pytest.mark.parametrize('old,new,message', [
    ('&tuner_loss_nl', '&other_nl', 'Missing'),
    ('num_time_windows=2', 'num_time_windows=7', 'divide evenly'),
    ('num_time_windows=2', 'num_time_windows=1.5', 'integer'),
    ('clubb_var_names(2)="wp2"', 'clubb_var_names(2)="thlm"', 'Duplicate'),
    ('benchmark_var_name(2)="wp2"', 'benchmark_var_name(2)=""', 'paired'),
    ('altitude_comparison_range=20,2940', 'altitude_comparison_range=9000,9100', 'model levels'),
    ('time_average_range=0,600', 'time_average_range=60,600', 'must match'),
])
def test_invalid_loss_configuration(prepared_loss, tmp_path, old, new, message):
    path, _, _ = prepared_loss
    changed = tmp_path / 'invalid.in'
    changed.write_text(path.read_text().replace(old, new))
    request = loss.loss_request_type(state=loss.active_request.state)
    with pytest.raises(ValueError, match=message):
        loss.init_loss_request(str(changed), 4, request)


def test_nonfinite_profile_and_runtime_error_penalties(prepared_loss, monkeypatch):
    _, _, params = prepared_loss
    healthy = loss.clubb_get_loss_for_params(params[:2])
    original = loss.advance_clubb_to_end
    def fail_column(state, *args, **kwargs):
        original(state, *args, **kwargs)
        state['err_info'] = state['err_info'].set_fatal(jnp.array([True, False]))
    monkeypatch.setattr(loss, 'advance_clubb_to_end', fail_column)
    result = loss.clubb_get_loss_for_params(params[:2])
    for values, expected, penalty in zip(result, healthy, loss.set_invalid_field_metric_outputs()):
        np.testing.assert_array_equal(values[..., 1], expected[..., 1])
        np.testing.assert_array_equal(values[..., 0], penalty)
    stats = loss.active_request.state['_jax_stats']
    bank, slot = loss.active_request.fields[0].stats_var_id
    buffers = list(stats.buffers)
    buffers[bank] = buffers[bank].at[slot, 0, :].set(jnp.nan)
    result = loss.calculate_field_loss(loss.active_request, stats._new(buffers=tuple(buffers)), 1)
    for values, penalty in zip(result, loss.set_invalid_field_metric_outputs()):
        assert np.isfinite(values).all()
        assert float(values[0, 0]) == penalty


def test_lifecycle_and_shape_errors(prepared_loss):
    path, _, _ = prepared_loss
    with pytest.raises(ValueError, match='still active'):
        loss.init_clubb_loss(str(path))
    with pytest.raises(ValueError, match='shape'):
        loss.clubb_get_loss_for_params(np.ones((2, 101)))
    loss.finalize_clubb_loss()
    loss.finalize_clubb_loss()
    assert loss.get_loss_time_window_count() == 1
    with pytest.raises(ValueError, match='requires init_clubb_loss'):
        loss.clubb_get_loss_for_params(np.ones((2, 102)))
