pipeline {

  agent any
  
  stages {
    stage('standard cases + multi_col with ifx') {
      steps {
        sh '''source /etc/profile.d/larson-group.sh
              module load intel netcdf-fortran
              ./compile.py
              ulimit -s 8388608
              run_scripts/run_scm_all.py -multicol 4 -max_iters 500 -out_dir driver_test/standalone_ifx
              run_scripts/run_scm_all.py -multicol 4 -max_iters 500 -out_dir driver_test/driver_ifx -driver_test
              run_scripts/run_bindiff_all.py output/driver_test/standalone_ifx output/driver_test/driver_ifx'''
      }
    }
    stage('min_cases + multi_col with nvhpc + openacc') {
      steps {
        sh '''source /etc/profile.d/larson-group.sh
              module load nvhpc netcdf-fortran
              ./compile.py -gpu openacc'''
        lock( "GPU_${env.NODE_NAME}" ) {
          sh '''ulimit -s 8388608
                run_scripts/run_scm_all.py -nproc 1 -min_cases -multicol 8 -max_iters 200 -out_dir driver_test/standalone_nvhpc -override penta_solve_method=2,tridiag_solve_method=2,l_lh_straight_mc=.true.
                run_scripts/run_scm_all.py -nproc 1 -min_cases -multicol 8 -max_iters 200 -out_dir driver_test/driver_nvhpc -driver_test -override penta_solve_method=2,tridiag_solve_method=2,l_lh_straight_mc=.true.'''
        }
        sh '''run_scripts/run_bindiff_all.py output/driver_test/standalone_nvhpc output/driver_test/driver_nvhpc'''
      }
    }
  }
  post {
    failure {
      script {
      if ( "${env.JOB_NAME}" == "clubb_driver_test" )
        // This command handles the email on failure feature of the jenkins test. This line is the same on every jenkins test.
      	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
