"""Curated equation and term metadata for the interactive CLUBB guide.

The displayed forms follow ``doc/CLUBBeqns.tex``.  The guide intentionally
focuses on the equations that connect CLUBB's prognosed moments, PDF closure,
and cloud/buoyancy diagnostics; it is a map into the full document, not a
replacement for its numerical-discretization derivations.
"""

from __future__ import annotations


PROCESS_META = {
    "state": ("Prognosed state", "The quantity whose tendency CLUBB advances."),
    "transport": ("Transport", "Moves an existing moment vertically or with the mean flow."),
    "production": ("Production", "Creates or removes a moment through resolved mean gradients."),
    "buoyancy": ("Buoyancy", "Couples thermodynamic density differences to vertical motion."),
    "pressure": ("Pressure", "Redistributes turbulent energy or decorrelates a turbulent flux."),
    "dissipation": ("Dissipation", "Relaxes turbulent moments on the CLUBB time scale."),
    "forcing": ("External forcing", "Comes from the host model or prescribed case forcing."),
    "numerical": ("Numerical safeguard", "Maintains bounds or stabilizes the discrete solution."),
    "pdf": ("PDF closure", "Diagnoses an unclosed moment from the assumed subgrid PDF."),
    "cloud": ("Cloud diagnostic", "Integrates the PDF across the saturation boundary."),
}

# The color meanings follow Table 1.1 of the official CLUBB-SILHS document.
OWNERSHIP_META = {
    "host": ("Host / physics", "Predicted by the host model, microphysics, or radiation."),
    "clubb_output": ("CLUBB → host", "Predicted by CLUBB and returned to the host model."),
    "clubb_internal": ("CLUBB internal", "Predicted and used internally by CLUBB."),
    "pdf": ("PDF diagnosed", "Calculated by integrating or diagnosing CLUBB's subgrid PDF."),
    "classical": ("Non-PDF closure", "Closed by a classical CLUBB parameterization rather than the PDF."),
}


def term(
    key,
    latex,
    code,
    process,
    title,
    meaning,
    obtained,
    why,
    *,
    ownership=None,
    units="Depends on the selected equation",
    source="doc/CLUBBeqns.tex",
):
    if ownership is None:
        ownership = {
            "forcing": "host",
            "numerical": "classical",
            "pressure": "classical",
            "dissipation": "classical",
            "pdf": "pdf",
            "cloud": "pdf",
            "buoyancy": "pdf",
        }.get(process, "clubb_internal")
    return {
        "key": key,
        "latex": latex,
        "code": code,
        "process": process,
        "ownership": ownership,
        "title": title,
        "meaning": meaning,
        "obtained": obtained,
        "why": why,
        "units": units,
        "source": source,
    }


def equation(
    identifier,
    title,
    lhs,
    summary,
    terms,
    *,
    note,
    source,
    family,
    lhs_owner="clubb_internal",
):
    return {
        "id": identifier,
        "title": title,
        "lhs": lhs,
        "summary": summary,
        "terms": tuple(terms),
        "note": note,
        "source": source,
        "family": family,
        "lhs_owner": lhs_owner,
    }


MA = {
    "code": "ma",
    "process": "transport",
    "title": "Mean advection",
    "meaning": "The mean vertical velocity carries the existing mean or turbulent moment through its vertical gradient.",
    "obtained": "Directly from the current mean vertical velocity and the vertical gradient of the quantity being advanced.",
    "why": "It relocates a profile without being a turbulence closure. In a host model this piece is often owned outside CLUBB.",
}
TA = {
    "code": "ta",
    "process": "transport",
    "title": "Turbulent advection",
    "meaning": "The divergence of a higher-order turbulent flux transports the moment between levels.",
    "obtained": "The flux inside the derivative is unclosed and is diagnosed by the PDF closure; CLUBB then takes its density-weighted vertical divergence.",
    "why": "This is the route by which PDF assumptions affect prognostic budgets. A wrong higher-order flux gives the wrong vertical redistribution.",
    "ownership": "pdf",
}
AC = {
    "code": "ac",
    "process": "production",
    "title": "Mean-flow stretching",
    "meaning": "A vertical gradient in mean vertical velocity stretches or compresses a turbulent vertical-velocity moment.",
    "obtained": "From the prognosed moment and the diagnosed vertical gradient of mean vertical velocity.",
    "why": "It can amplify or weaken vertical-velocity moments even without buoyancy production.",
}
TP = {
    "code": "tp",
    "process": "production",
    "title": "Turbulent production",
    "meaning": "A turbulent flux acting against a mean scalar gradient creates or destroys variance or covariance.",
    "obtained": "From prognosed second moments and mean vertical gradients.",
    "why": "This is the main conversion from mean-profile structure into scalar variance and turbulent scalar flux.",
}
BP = {
    "code": "bp",
    "process": "buoyancy",
    "title": "Buoyancy production",
    "meaning": "Density or virtual-potential-temperature fluctuations accelerate parcels and alter vertical-velocity moments or scalar fluxes.",
    "obtained": "The required virtual-potential-temperature covariance is diagnosed from dry thermodynamic moments plus PDF-derived liquid-water covariances.",
    "why": "This is where cloud diagnostics such as w′r_c′ feed back into the w′², w′³, w′r_t′, and w′θ_l′ budgets.",
}
PR = {
    "process": "pressure",
    "title": "Pressure redistribution",
    "meaning": "Pressure fluctuations redistribute turbulent energy and decorrelate vertical turbulent fluxes.",
    "obtained": "A parameterized return-to-isotropy/return-to-equilibrium closure using tunable coefficients and the turbulent time scale.",
    "why": "Pressure prevents vertical turbulence and scalar fluxes from growing without bound and redistributes energy among directions.",
}
DP = {
    "process": "dissipation",
    "title": "Dissipation or regularization",
    "meaning": "Small-scale turbulence relaxes a moment, while explicit vertical diffusion smooths sharp grid-scale structure.",
    "obtained": "From the moment, a CLUBB time scale, a lower tolerance where applicable, and an eddy-diffusivity coefficient.",
    "why": "These terms provide the physical sink and numerical regularization that balance production.",
}


BUDGET_EQUATIONS = (
    equation(
        "mean-rt",
        "Mean total water",
        r"\frac{\partial \overline{r_t}}{\partial t}",
        "CLUBB changes mean moisture through transport plus externally supplied tendencies.",
        (
            term("ma", r"-\overline{w}\,\frac{\partial\overline{r_t}}{\partial z}", **{**MA, "ownership": "host"}),
            term("ta", r"-\frac{1}{\rho_s}\frac{\partial(\rho_s\overline{w'r_t'})}{\partial z}", **{**TA, "ownership": "clubb_output"}),
            term(
                "ls",
                r"+\left.\frac{\partial\overline{r_t}}{\partial t}\right|_{ls}",
                "ls",
                "forcing",
                "Large-scale moisture forcing",
                "Prescribed or host-model moisture advection that is not produced by CLUBB turbulence.",
                "Read from the case forcing or supplied by the host model.",
                "It can moisten or dry the whole column independently of the turbulent flux divergence.",
            ),
            term(
                "adjust",
                r"+\;\mathcal{A}_{cl,mfl,tacl,sdmp}",
                "cl/mfl/tacl/sdmp",
                "numerical",
                "Bound and stability adjustments",
                "A compact display of clipping, the monotonic flux limiter, turbulent-advection clipping, and sponge damping.",
                "Applied outside or around the main physical advance where their respective safeguards are enabled.",
                "They matter when reconciling a saved before/after change with only the terms inside an advance routine.",
            ),
        ),
        note="The host-interface form uses q_t in some configurations; CLUBB's internal equation document uses r_t.",
        source="CLUBBeqns: eq_rtm · advance_xm_wpxp",
        family="budget",
        lhs_owner="host",
    ),
    equation(
        "mean-thl",
        "Mean liquid-water potential temperature",
        r"\frac{\partial \overline{\theta_l}}{\partial t}",
        "Mean thermodynamic energy responds to turbulent transport, radiation, and external tendencies.",
        (
            term("ma", r"-\overline{w}\,\frac{\partial\overline{\theta_l}}{\partial z}", **{**MA, "ownership": "host"}),
            term("ta", r"-\frac{1}{\rho_s}\frac{\partial(\rho_s\overline{w'\theta_l'})}{\partial z}", **{**TA, "ownership": "clubb_output"}),
            term(
                "rad",
                r"+\overline{R}",
                "rad",
                "forcing",
                "Radiative heating",
                "Heating or cooling of the layer by radiation.",
                "Supplied by a radiation calculation or prescribed by the case.",
                "Radiative cooling near cloud top can strongly drive boundary-layer turbulence.",
                units="K s⁻¹",
            ),
            term(
                "ls",
                r"+\left.\frac{\partial\overline{\theta_l}}{\partial t}\right|_{ls}",
                "ls",
                "forcing",
                "Large-scale temperature forcing",
                "The non-turbulent temperature tendency imposed by resolved-scale dynamics.",
                "Read from the case forcing or supplied by the host model.",
                "It sets the environment in which CLUBB's turbulent transport operates.",
            ),
            term(
                "adjust",
                r"+\;\mathcal{A}_{cl,mfl,tacl,sdmp}",
                "cl/mfl/tacl/sdmp",
                "numerical",
                "Bound and stability adjustments",
                "Clipping, flux limiting, turbulent-advection clipping, and sponge damping grouped for readability.",
                "Applied by CLUBB's safeguard stages when enabled.",
                "They explain changes that are not represented by the core advance budget alone.",
            ),
        ),
        note="θ_l removes the leading-order latent-heating jump, making it a convenient approximately conserved thermodynamic variable.",
        source="CLUBBeqns: eq_thlm · advance_xm_wpxp",
        family="budget",
        lhs_owner="host",
    ),
    equation(
        "wp2",
        "Vertical-velocity variance",
        r"\frac{\partial\overline{w'^2}}{\partial t}",
        "The central energy-like equation for the strength of vertical turbulence.",
        (
            term("ma", r"-\overline{w}\,\frac{\partial\overline{w'^2}}{\partial z}", **MA),
            term("ta", r"-\frac{1}{\rho_s}\frac{\partial(\rho_s\overline{w'^3})}{\partial z}", **TA),
            term("ac", r"-2\overline{w'^2}\frac{\partial\overline{w}}{\partial z}", **AC),
            term("bp", r"+\frac{2g}{\theta_{vs}}\overline{w'\theta_v'}", **BP),
            term("pr1", r"-\frac{C_4}{\tau}\left(\overline{w'^2}-\frac{2}{3}\overline e\right)", "pr1", **PR),
            term("pr23", r"+\;\mathcal{P}_{rapid}(C_5;\, shear,buoyancy)", "pr2+pr3", **PR),
            term("dp1", r"-\frac{C_1}{\tau}\left(\overline{w'^2}-w_{tol}^2\right)", "dp1", **DP),
            term("dp2", r"+\frac{\partial}{\partial z}\left[(K_{w1}+\nu_1)\frac{\partial\overline{w'^2}}{\partial z}\right]", "dp2", **DP),
            term(
                "adjust",
                r"+\left.\frac{\partial\overline{w'^2}}{\partial t}\right|_{pd,cl}",
                "pd/cl",
                "numerical",
                "Positive-definite and clipping adjustments",
                "Corrections that keep the variance realizable and within explicit numerical bounds.",
                "Applied by CLUBB's hole-filling and clipping stages.",
                "A budget assembled only from advance_wp2_wp3 terms intentionally excludes these external corrections.",
            ),
        ),
        note="The buoyancy term contains w′θ_v′, which depends on w′r_c′ after the moist thermodynamic linearization.",
        source="CLUBBeqns: eq_wp2 · advance_wp2_wp3",
        family="budget",
    ),
    equation(
        "scalar-variance",
        "Scalar variance (ψ = r_t or θ_l)",
        r"\frac{\partial\overline{\psi'^2}}{\partial t}",
        "One template explains both total-water and liquid-water-potential-temperature variance.",
        (
            term("ma", r"-\overline{w}\,\frac{\partial\overline{\psi'^2}}{\partial z}", **MA),
            term("ta", r"-\frac{1}{\rho_s}\frac{\partial(\rho_s\overline{w'\psi'^2})}{\partial z}", **TA),
            term("tp", r"-2\overline{w'\psi'}\frac{\partial\overline\psi}{\partial z}", **TP),
            term("dp1", r"-\frac{C_2}{\tau}\left(\overline{\psi'^2}-\psi_{tol}^2\right)", "dp1", **DP),
            term("dp2", r"+\frac{\partial}{\partial z}\left[(K_{w2}+\nu_2)\frac{\partial\overline{\psi'^2}}{\partial z}\right]", "dp2", **DP),
            term(
                "adjust",
                r"+\left.\frac{\partial\overline{\psi'^2}}{\partial t}\right|_{pd,cl}",
                "pd/cl",
                "numerical",
                "Variance safeguards",
                "Positive-definite hole filling and explicit clipping keep scalar variance realizable.",
                "Applied after the core budget as needed.",
                "Boundary and clipping changes should not be mistaken for a failure of the interior budget equation.",
            ),
        ),
        note="The PDF closes w′ψ′²; the prognostic equation does not carry that third-order moment independently.",
        source="CLUBBeqns: eq_rtp2 / eq_thlp2 · advance_xp2_xpyp",
        family="budget",
    ),
    equation(
        "scalar-covariance",
        "Moisture–temperature covariance",
        r"\frac{\partial\overline{r_t'\theta_l'}}{\partial t}",
        "Tracks whether moist anomalies also tend to be warm or cool in θ_l coordinates.",
        (
            term("ma", r"-\overline{w}\,\frac{\partial\overline{r_t'\theta_l'}}{\partial z}", **MA),
            term("ta", r"-\frac{1}{\rho_s}\frac{\partial(\rho_s\overline{w'r_t'\theta_l'})}{\partial z}", **TA),
            term("tp1", r"-\overline{w'r_t'}\frac{\partial\overline{\theta_l}}{\partial z}", **{**TP, "code": "tp1"}),
            term("tp2", r"-\overline{w'\theta_l'}\frac{\partial\overline{r_t}}{\partial z}", **{**TP, "code": "tp2"}),
            term("dp1", r"-\frac{C_2}{\tau}\overline{r_t'\theta_l'}", "dp1", **DP),
            term("dp2", r"+\frac{\partial}{\partial z}\left[(K_{w2}+\nu_2)\frac{\partial\overline{r_t'\theta_l'}}{\partial z}\right]", "dp2", **DP),
        ),
        note="This covariance controls the orientation of the thermodynamic PDF and enters saturation variance.",
        source="CLUBBeqns: eq_rtpthlp · advance_xp2_xpyp",
        family="budget",
    ),
    equation(
        "scalar-flux",
        "Vertical scalar flux (ψ = r_t or θ_l)",
        r"\frac{\partial\overline{w'\psi'}}{\partial t}",
        "The equation that turns scalar gradients and buoyancy into vertical turbulent transport.",
        (
            term("ma", r"-\overline{w}\,\frac{\partial\overline{w'\psi'}}{\partial z}", **MA),
            term("ta", r"-\frac{1}{\rho_s}\frac{\partial(\rho_s\overline{w'^2\psi'})}{\partial z}", **TA),
            term("tp", r"-\overline{w'^2}\frac{\partial\overline\psi}{\partial z}", **TP),
            term("ac", r"-\overline{w'\psi'}\frac{\partial\overline w}{\partial z}", **AC),
            term("bp", r"+\frac{g}{\theta_{vs}}\overline{\psi'\theta_v'}", **BP),
            term("pr1", r"-\frac{C_6}{\tau}\overline{w'\psi'}", "pr1", **PR),
            term("pr23", r"+\;\mathcal{P}_{rapid}(C_7;\,shear,buoyancy)", "pr2+pr3", **PR),
            term("dp1", r"+\frac{\partial}{\partial z}\left[(K_{w6}+\nu_6)\frac{\partial\overline{w'\psi'}}{\partial z}\right]", "dp1", **DP),
        ),
        note="For ψ=r_t this is wprtp; for ψ=θ_l it is wpthlp. Both are prognosed and feed the mean equations.",
        source="CLUBBeqns: eq_wprtp / eq_wpthlp · advance_xm_wpxp",
        family="budget",
    ),
    equation(
        "wp3",
        "Vertical-velocity third moment",
        r"\frac{\partial\overline{w'^3}}{\partial t}",
        "Controls vertical-velocity skewness and therefore how the PDF separates updraft and environment.",
        (
            term("ma", r"-\overline{w}\,\frac{\partial\overline{w'^3}}{\partial z}", **MA),
            term("ta", r"-\frac{1}{\rho_s}\frac{\partial(\rho_s\overline{w'^4})}{\partial z}", **TA),
            term("tp", r"+3\frac{\overline{w'^2}}{\rho_s}\frac{\partial(\rho_s\overline{w'^2})}{\partial z}", **TP),
            term("ac", r"-3\overline{w'^3}\frac{\partial\overline w}{\partial z}", **AC),
            term("bp1", r"+\frac{3g}{\theta_{vs}}\overline{w'^2\theta_v'}", **{**BP, "code": "bp1"}),
            term("bp2", r"+\;\mathcal{B}_{nonlocal}(C_{15},K_m)", **{**BP, "code": "bp2"}),
            term("pr1", r"-\frac{C_8}{\tau}(C_{8b}Sk_w^4+1)\overline{w'^3}", "pr1", **PR),
            term("pr2", r"+\;\mathcal{P}_{rapid}(C_{11})", "pr2", **PR),
            term("dp1", r"+\frac{\partial}{\partial z}\left[(K_{w8}+\nu_8)\frac{\partial\overline{w'^3}}{\partial z}\right]", "dp1", **DP),
        ),
        note="w′⁴ and w′²θ_v′ are PDF-diagnosed. wp2 and wp3 are solved together in advance_wp2_wp3.",
        source="CLUBBeqns: eq_wp3 · advance_wp2_wp3",
        family="budget",
    ),
)


PDF_EQUATIONS = (
    equation(
        "mixture-pdf",
        "The subgrid PDF (simplified non-precipitating form)",
        r"P(\mathbf{x})",
        "Represent a grid box as two overlapping multivariate Gaussian air populations.",
        (
            term(
                "component-1",
                r"a\,\mathcal{N}(\mathbf{x};\mu_1,\Sigma_1)",
                "component 1",
                "pdf",
                "First Gaussian component",
                "A probability-weighted air population with its own center and covariance geometry.",
                "ADG1 or another PDF diagnosis determines the weight a, mean vector μ₁, and covariance matrix Σ₁ from the available grid moments plus structural assumptions.",
                "This component often represents a coherent updraft or plume, but the mathematics does not require that label.",
                units="probability density",
                source="CLUBB-SILHS Eq. 3.46 (simplified here)",
            ),
            term(
                "component-2",
                r"+(1-a)\,\mathcal{N}(\mathbf{x};\mu_2,\Sigma_2)",
                "component 2",
                "pdf",
                "Second Gaussian component",
                "The complementary air population, with probability 1−a and its own center and covariance geometry.",
                "Its parameters are diagnosed simultaneously so the complete mixture reproduces the selected grid moments.",
                "Two components allow skewness and distinct populations, but the moments do not uniquely determine every free component parameter.",
                units="probability density",
                source="CLUBB-SILHS Eq. 3.46 (simplified here)",
            ),
        ),
        note="The full CLUBB-SILHS PDF can also include precipitating lognormal variables and delta functions at zero; this card isolates the w–r_t–θ_l core used in this lesson.",
        source="CLUBB-SILHS Eq. 3.46 · PDF diagnosis routines",
        family="pdf",
        lhs_owner="pdf",
    ),
    equation(
        "pdf-expectation",
        "How a PDF closes a missing moment",
        r"\overline{f(\mathbf{x})}",
        "Any required subgrid diagnostic is an expectation of the relevant function under the assumed PDF.",
        (
            term(
                "integral",
                r"\int f(\mathbf{x})P(\mathbf{x})\,d\mathbf{x}",
                "PDF integral",
                "pdf",
                "PDF expectation",
                "Sum the contribution of every possible subgrid state, weighted by its probability density.",
                "CLUBB evaluates convenient Gaussian moments analytically; SILHS samples the PDF for less convenient process integrals.",
                "This single idea produces higher-order transport moments, cloud fraction, liquid water, and many microphysical averages—the integrand f is what changes.",
                source="CLUBB-SILHS PDF closure and SILHS chapters",
            ),
        ),
        note="For example, choose f=w′²r_t′ for flux transport, or f=H(χ) for cloud fraction.",
        source="CLUBB-SILHS Eq. 3.49 and SILHS integration section",
        family="pdf",
        lhs_owner="pdf",
    ),
    equation(
        "correlations",
        "Resolved moment correlations",
        r"c_{w\psi}",
        "Normalize a covariance so PDF shape controls can use a dimensionless coupling strength.",
        (
            term(
                "corr",
                r"\frac{\overline{w'\psi'}}{\sqrt{\overline{w'^2}}\sqrt{\overline{\psi'^2}}}",
                "c_wψ",
                "pdf",
                "w–scalar correlation",
                "The fraction of the possible linear covariance between vertical velocity and scalar ψ.",
                "Computed from prognosed covariance and variances; ψ is r_t or θ_l.",
                "ADG1 uses these correlations to restrict component widths, so they strongly influence the diagnosed plume geometry.",
                units="dimensionless",
                source="CLUBBeqns: eq_cwrt / eq_cwthl",
            ),
        ),
        note="A covariance can be large because either variance is large; correlation isolates geometric alignment.",
        source="CLUBBeqns: eq_cwrt / eq_cwthl",
        family="pdf",
        lhs_owner="pdf",
    ),
    equation(
        "plume-width",
        "ADG1 within-plume width",
        r"\widetilde{\sigma}_w^2",
        "ADG1 ties each component's internal w width to the strongest w–scalar correlation.",
        (
            term(
                "gamma",
                r"\gamma",
                "gamma",
                "pdf",
                "Width parameter γ",
                "A tunable ceiling on normalized within-component vertical-velocity variance.",
                "Read from CLUBB's PDF closure parameters.",
                "It limits how much total w variance may live inside components rather than between their means.",
                units="dimensionless",
                source="CLUBBeqns: eq_sc",
            ),
            term(
                "corr-limit",
                r"\left[1-\max(c_{w\theta_l}^2,c_{wr_t}^2)\right]",
                "correlation limiter",
                "pdf",
                "Correlation width restriction",
                "Stronger resolved w–scalar correlation narrows the Gaussian components in w.",
                "Computed from the two prognosed w–scalar correlations.",
                "This is a major ADG1 structural assumption: component geometry is not freely diagnosed from all possible covariances.",
                units="dimensionless",
                source="CLUBBeqns: eq_sc",
            ),
        ),
        note="This closure is one reason matching the grid moments does not guarantee the right cloudy tail.",
        source="CLUBBeqns: eq_sc · setup_clubb_pdf_params",
        family="pdf",
        lhs_owner="pdf",
    ),
    equation(
        "wp4",
        "Fourth vertical-velocity moment",
        r"\overline{w'^4}",
        "The PDF supplies the fourth moment needed to transport w′³.",
        (
            term(
                "width-part",
                r"\overline{w'^2}^{\,2}(a_3+3)",
                "width contribution",
                "pdf",
                "Within-component width contribution",
                "The Gaussian-like part of kurtosis modified by the diagnosed component width.",
                "Computed from w′² and the PDF width functions a₁–a₃.",
                "It sets the baseline tail weight even when w skewness is weak.",
                source="CLUBBeqns: eq_wp4",
            ),
            term(
                "skew-part",
                r"+a_1\frac{\overline{w'^3}^{\,2}}{\overline{w'^2}}",
                "skewness contribution",
                "pdf",
                "Skewness contribution",
                "Adds fourth-moment magnitude when the vertical-velocity PDF is asymmetric.",
                "Computed from prognosed w′² and w′³ plus a₁.",
                "It couples the prognosed skewness directly into the wp3 transport budget.",
                source="CLUBBeqns: eq_wp4",
            ),
        ),
        note="The wp3 equation needs w′⁴, but CLUBB does not prognose it; this is a closure point.",
        source="CLUBBeqns: eq_wp4 · calc_wp4_pdf",
        family="pdf",
        lhs_owner="pdf",
    ),
    equation(
        "wp2psi",
        "Flux-transport closure",
        r"\overline{w'^2\psi'}",
        "Closes the higher-order flux that transports w′ψ′.",
        (
            term(
                "closure",
                r"a_1\frac{\overline{w'^3}}{\overline{w'^2}}\overline{w'\psi'}",
                "PDF",
                "pdf",
                "PDF flux-transport closure",
                "Scales the existing w–scalar flux by a skewness velocity scale and a component-width correction.",
                "Diagnosed from prognosed w′², w′³, w′ψ′ and the PDF parameter a₁.",
                "An error here changes turbulent advection in the w′r_t′ or w′θ_l′ equation.",
                source="CLUBBeqns: eq_wp2rtp / eq_wp2thlp",
            ),
        ),
        note="ψ may be r_t or θ_l. This is the direct bridge from PDF shape to scalar-flux transport.",
        source="CLUBBeqns: eq_wp2rtp / eq_wp2thlp · calc_wp2xp_pdf",
        family="pdf",
        lhs_owner="pdf",
    ),
    equation(
        "wppsi2",
        "Variance-transport closure",
        r"\overline{w'\psi'^2}",
        "Closes vertical transport of scalar variance using a blend controlled by β.",
        (
            term(
                "variance-route",
                r"\frac{\beta}{3}a_1\frac{\overline{w'^3}}{\overline{w'^2}}\overline{\psi'^2}",
                "β route",
                "pdf",
                "Variance-based route",
                "Uses scalar variance directly with the skewness velocity scale.",
                "Computed from prognosed moments and the tunable β blend.",
                "Increasing β emphasizes total scalar variance rather than covariance aligned specifically with w.",
                source="CLUBBeqns: eq_wprtp2 / eq_wpthlp2",
            ),
            term(
                "flux-route",
                r"+\left(1-\frac{\beta}{3}\right)a_2\frac{\overline{w'^3}}{\overline{w'^2}^{\,2}}\overline{w'\psi'}^{\,2}",
                "covariance route",
                "pdf",
                "Flux-aligned route",
                "Uses the squared w–scalar covariance, emphasizing scalar variability aligned with vertical motion.",
                "Computed from prognosed moments and a₂.",
                "This route can preserve the shape of a strongly coupled plume but remains constrained by the assumed PDF geometry.",
                source="CLUBBeqns: eq_wprtp2 / eq_wpthlp2",
            ),
        ),
        note="The β experiment changes the blend, but it cannot create geometric freedom absent from the PDF family.",
        source="CLUBBeqns: eq_wprtp2 / eq_wpthlp2 · calc_wpxp2_pdf",
        family="pdf",
        lhs_owner="pdf",
    ),
    equation(
        "triple-transport",
        "Mixed thermodynamic transport",
        r"\overline{w'r_t'\theta_l'}",
        "The third-order covariance transports the prognosed r_t–θ_l covariance.",
        (
            term(
                "cov-route",
                r"\frac{\beta}{3}a_1\frac{\overline{w'^3}}{\overline{w'^2}}\overline{r_t'\theta_l'}",
                "β route",
                "pdf",
                "Covariance-based route",
                "Transports the existing thermodynamic covariance with the PDF skewness velocity scale.",
                "Computed from prognosed covariance and w moments.",
                "It carries the full r_t–θ_l relationship, whether or not that relationship aligns with w.",
                source="CLUBBeqns: eq_wprtpthlp",
            ),
            term(
                "flux-product",
                r"+\left(1-\frac{\beta}{3}\right)a_2\frac{\overline{w'^3}}{\overline{w'^2}^{\,2}}\overline{w'r_t'}\overline{w'\theta_l'}",
                "flux-product route",
                "pdf",
                "Flux-product route",
                "Builds mixed transport from the two scalar fluxes that share vertical velocity.",
                "Computed from prognosed w′r_t′ and w′θ_l′.",
                "It assumes a particular relationship among the three variables rather than diagnosing arbitrary trivariate structure.",
                source="CLUBBeqns: eq_wprtpthlp",
            ),
        ),
        note="This is one place where the closure encodes trivariate structure using only the available lower-order moments.",
        source="CLUBBeqns: eq_wprtpthlp · calc_wpxpyp_pdf",
        family="pdf",
        lhs_owner="pdf",
    ),
)


CLOUD_EQUATIONS = (
    equation(
        "theta-v",
        "Virtual-potential-temperature covariance",
        r"\overline{\chi'\theta_v'}",
        "Decomposes moist buoyancy into θ_l, total-water, and liquid-water covariances.",
        (
            term(
                "dry",
                r"\overline{\chi'\theta_l'}",
                "dry thermodynamic",
                "buoyancy",
                "Liquid-water potential-temperature part",
                "The dry/thermal contribution to virtual-temperature covariance.",
                "Usually already prognosed or algebraically available for χ=w, r_t, θ_l, or w′².",
                "This term can be LES-consistent while the total buoyancy covariance is wrong because the cloud-water part is separate.",
                ownership="clubb_internal",
                source="CLUBBeqns: PDF closure / buoyancy terms",
            ),
            term(
                "vapor",
                r"+A\,\overline{\chi'r_t'}",
                "vapor",
                "buoyancy",
                "Total-water contribution",
                "The virtual effect of water vapor, with A roughly 200 K in the equation document's scaling.",
                "From a prognosed or closed χ–r_t covariance.",
                "For χ=w this contribution uses w′r_t′, one of CLUBB's prognosed fluxes.",
                ownership="clubb_internal",
                source="CLUBBeqns: PDF closure / buoyancy terms",
            ),
            term(
                "liquid",
                r"+B\,\overline{\chi'r_l'}",
                "liquid cloud",
                "cloud",
                "Liquid-water contribution",
                "The strong latent/condensate correction, with B roughly 2000 K and a sign determined by the thermodynamic coefficient convention.",
                "The liquid-water covariance is integrated from the diagnosed PDF.",
                "Its large coefficient makes a modest w′r_c′ error capable of dominating the w′θ_v′ error.",
                source="CLUBBeqns: PDF closure / buoyancy terms · pdf_closure_module",
            ),
        ),
        note="Set χ=w to obtain w′θ_v′, the buoyancy flux in the wp2 budget.",
        source="CLUBBeqns: PDF closure / buoyancy terms · pdf_closure_module lines near wpthvp",
        family="cloud",
        lhs_owner="pdf",
    ),
    equation(
        "cloud-fraction-component",
        "Cloud fraction of component i",
        r"C_i",
        "Integrates one Gaussian across its linearized saturation boundary.",
        (
            term(
                "erf",
                r"\frac{1}{2}\left[1+\operatorname{erf}\left(\frac{s_i}{\sqrt{2}\sigma_{si}}\right)\right]",
                "C_i",
                "cloud",
                "Gaussian cloudy probability",
                "The probability that extended cloud water is positive within PDF component i.",
                "Compute the component mean saturation excess s_i and its standard deviation σ_si, then evaluate the normal cumulative distribution.",
                "Cloud fraction depends mainly on the normalized distance s_i/σ_si from the cloud boundary, not on either quantity alone.",
                units="0–1",
                source="CLUBBeqns: eq_C_gauss · calc_liquid_cloud_frac_component",
            ),
        ),
        note="This is analytic Gaussian integration; SILHS is used for processes whose PDF integrals are less convenient analytically.",
        source="CLUBBeqns: eq_C_gauss · calc_liquid_cloud_frac_component",
        family="cloud",
        lhs_owner="pdf",
    ),
    equation(
        "liquid-water-component",
        "Mean liquid water of component i",
        r"r_{li}",
        "Combines the cloudy portion's mean saturation excess with the Gaussian tail crossing the boundary.",
        (
            term(
                "mean-excess",
                r"s_i C_i",
                "mean excess",
                "cloud",
                "Cloudy mean contribution",
                "Mean saturation excess multiplied by the component's cloudy probability.",
                "From s_i and the diagnosed component cloud fraction C_i.",
                "Dominates when the component mean lies well inside cloud.",
                source="CLUBBeqns: eq_rl_gauss",
            ),
            term(
                "tail",
                r"+\frac{\sigma_{si}}{\sqrt{2\pi}}\exp\left[-\frac{1}{2}\left(\frac{s_i}{\sigma_{si}}\right)^2\right]",
                "Gaussian tail",
                "cloud",
                "Boundary-crossing tail contribution",
                "Liquid water contributed by the cloudy tail even when the component mean is clear.",
                "Analytic first moment of the positive part of a normal saturation variable.",
                "This is why a mostly clear Gaussian can still produce nonzero cloud water.",
                source="CLUBBeqns: eq_rl_gauss",
            ),
        ),
        note="The nonlinear max(s,0) cloud boundary is what turns an otherwise Gaussian PDF into asymmetric cloud diagnostics.",
        source="CLUBBeqns: eq_rl_gauss · calc_liquid_cloud_frac_component",
        family="cloud",
        lhs_owner="pdf",
    ),
    equation(
        "mixture-cloud",
        "Layer cloud fraction",
        r"\overline C",
        "Combine the two component cloud probabilities using the diagnosed mixture fraction.",
        (
            term(
                "component-1",
                r"aC_1",
                "component 1",
                "cloud",
                "Component-1 cloud contribution",
                "Cloud probability in the first Gaussian weighted by its mixture fraction a.",
                "From the PDF mixture fraction and C₁.",
                "A rare component can have high C₁ but still contribute little to total cloud fraction if a is small.",
                units="0–1",
                source="CLUBBeqns: layer-averaged cloud properties",
            ),
            term(
                "component-2",
                r"+(1-a)C_2",
                "component 2",
                "cloud",
                "Component-2 cloud contribution",
                "Cloud probability in the second Gaussian weighted by its complementary mixture fraction.",
                "From a and C₂.",
                "The common environmental component often dominates probability even when a rare plume dominates transport.",
                units="0–1",
                source="CLUBBeqns: layer-averaged cloud properties",
            ),
        ),
        note="Mean liquid water uses the same mixture weighting: r̄_l = a r_l1 + (1−a) r_l2.",
        source="CLUBBeqns: layer-averaged cloud properties",
        family="cloud",
        lhs_owner="pdf",
    ),
    equation(
        "wprl",
        "Vertical liquid-water flux",
        r"\overline{w'r_l'}",
        "Measures whether cloud water preferentially resides in rising or sinking subgrid air.",
        (
            term(
                "component-1",
                r"a(w_1-\overline w)r_{l1}",
                "component 1",
                "cloud",
                "First-component transport",
                "The first component's vertical-velocity displacement times its diagnosed liquid water and probability.",
                "From the diagnosed PDF component center, mixture weight, and analytic liquid-water integral.",
                "A small component can dominate if both its upward displacement and liquid water are large.",
                source="CLUBBeqns: layer-averaged cloud properties",
            ),
            term(
                "component-2",
                r"+(1-a)(w_2-\overline w)r_{l2}",
                "component 2",
                "cloud",
                "Second-component transport",
                "The complementary component's contribution to the liquid-water covariance.",
                "Diagnosed in the same way as component 1.",
                "Its sign may compensate the rare updraft, so the covariance is not simply upward-cloud importance.",
                source="CLUBBeqns: layer-averaged cloud properties",
            ),
        ),
        note="In current source, optional within-component w–χ correlation can add transport beyond the between-component expression shown in the classic equation document.",
        source="CLUBBeqns: layer-averaged cloud properties · calc_xprcp_component",
        family="cloud",
        lhs_owner="pdf",
    ),
    equation(
        "wpthv-code",
        "Buoyancy flux assembled in CLUBB",
        r"\overline{w'\theta_v'}",
        "The source-code form that connects the investigated cloud-water flux directly to wp2 buoyancy production.",
        (
            term(
                "thl",
                r"\overline{w'\theta_l'}",
                "wpthlp",
                "buoyancy",
                "Dry thermodynamic flux",
                "Vertical flux of liquid-water potential temperature.",
                "Prognosed by CLUBB's scalar-flux equation.",
                "If this agrees with LES, it is unlikely to explain a large residual in w′θ_v′ by itself.",
                ownership="clubb_internal",
                source="pdf_closure_module.F90: wpthvp assignment",
            ),
            term(
                "rt",
                r"+\epsilon_1\theta_{vs}\overline{w'r_t'}",
                "wprtp",
                "buoyancy",
                "Water-vapor virtual effect",
                "Converts total-water flux into its virtual-temperature contribution.",
                "Uses prognosed w′r_t′ and the dry base-state θ_v.",
                "This is the second LES-comparable piece of the buoyancy-flux reconstruction.",
                ownership="clubb_internal",
                source="pdf_closure_module.F90: wpthvp assignment",
            ),
            term(
                "rc",
                r"+c_{r_c}\overline{w'r_c'}",
                "wprcp",
                "cloud",
                "Cloud-water correction",
                "The liquid-water covariance correction to virtual potential temperature.",
                "w′r_c′ is diagnosed from the assumed PDF and multiplied by a thermodynamic coefficient.",
                "When w′θ_l′ and w′r_t′ agree with LES but w′θ_v′ does not, this term isolates the PDF cloud-transport diagnosis as the likely source.",
                source="pdf_closure_module.F90: wpthvp assignment",
            ),
        ),
        note="The exact coefficient includes the linearized moist thermodynamics and hydrometeor corrections used by the active configuration.",
        source="src/CLUBB_core/pdf_closure_module.F90 · wpthvp assignment",
        family="cloud",
        lhs_owner="pdf",
    ),
)


EQUATION_GROUPS = (
    {
        "value": "budgets",
        "label": "Prognostic budgets",
        "eyebrow": "What CLUBB advances",
        "intro": "Click a colored budget term to see its physical role, how CLUBB obtains it, and why it matters.",
        "equations": BUDGET_EQUATIONS,
    },
    {
        "value": "pdf",
        "label": "PDF closures",
        "eyebrow": "How missing moments are supplied",
        "intro": "These equations turn prognosed lower-order moments into the higher-order transport moments needed on the right-hand sides above.",
        "equations": PDF_EQUATIONS,
    },
    {
        "value": "cloud",
        "label": "Cloud & buoyancy",
        "eyebrow": "How the PDF affects dynamics",
        "intro": "The saturation integral diagnoses cloud properties, then liquid-water covariances enter virtual-temperature and buoyancy terms.",
        "equations": CLOUD_EQUATIONS,
    },
)


ABBREVIATIONS = (
    ("ma", "mean advection"),
    ("ta", "turbulent advection / flux divergence"),
    ("tp", "turbulent production by a mean gradient"),
    ("ac", "mean-flow stretching/compression"),
    ("bp", "buoyancy production"),
    ("pr", "pressure redistribution or decorrelation"),
    ("dp", "dissipation/diffusion parameterization"),
    ("pd", "positive-definite hole filling"),
    ("cl", "explicit clipping"),
    ("mfl", "monotonic flux limiter"),
    ("tacl", "turbulent-advection clipping"),
    ("sdmp", "sponge-layer damping"),
)


NOTATION = (
    (r"\overline{x}", "grid-box or ensemble mean"),
    (r"x'", "departure from that mean"),
    (r"\overline{x'y'}", "covariance; positive means anomalies tend to share a sign"),
    (r"r_t", "total-water mixing ratio"),
    (r"r_c\;(r_l)", "cloud liquid-water mixing ratio (notation varies by context)"),
    (r"\theta_l", "liquid-water potential temperature"),
    (r"\theta_v", "virtual potential temperature, the thermodynamic buoyancy variable"),
    (r"\rho_s,\theta_{vs}", "dry static base-state density and virtual potential temperature"),
    (r"\tau", "CLUBB turbulent time scale, limited by τ_max"),
    (r"a", "probability/mixture fraction of PDF component 1"),
)


def iter_term_occurrences():
    """Yield unique occurrence IDs and their equation-enriched metadata."""
    for group in EQUATION_GROUPS:
        for eq in group["equations"]:
            for position, item in enumerate(eq["terms"]):
                occurrence = f"{eq['id']}--{position}--{item['key']}"
                yield occurrence, {
                    **item,
                    "equation_title": eq["title"],
                    "equation_lhs": eq["lhs"],
                    "equation_source": eq["source"],
                }


TERM_OCCURRENCES = dict(iter_term_occurrences())
