pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        sh '''compile/compile.bash -c config/linux_x86_64_ifort.bash'''
      }
    }
    stage('Run') {
      steps {
         sh '''source /opt/intel/bin/ifortvars.sh intel64
               run_scripts/run_scm_all.bash'''
      }
    }
  }
  post { 
    always {
      cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenSuccess: true, cleanWhenUnstable: true)
    }
    failure {
      emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
    }
  }
}
