pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        sh '''source /etc/profile.d/larson-group.sh
              module load gcc netcdf-fortran
              ./compile.py -debug'''
      }
    }
    stage('Run Jax Python vs Fortran cases') {
      steps {
        sh '''source /etc/profile.d/larson-group.sh
              module load gcc netcdf-fortran
              ulimit -s 8388608
              python3 tests/run_jax_vs_fortran_cases.py -debug 0 -stats input/stats/standard_stats.in --max-iters 10''' //our code in jax is really sloow -> use faster tests
      }
    }
  }
  post {
    always {
      // Certain logical functions like IF statements or TRY-CATCH blocks can only operate while in a script{} block
      script {
      // This cleans out the test workspace so the next run has a fresh start
      // However this only occurs when the test is named clubb_python_test
      // This is to prevent the branch and copy tests from deleting thier workspaces so they are available for debugging
      if ( "${env.JOB_NAME}" == "compare_jax_vs_fortran" )
      	cleanWs(cleanWhenFailure: true, cleanWhenSuccess: true, cleanWhenUnstable: true)
      }
    }
    failure {
      script {
      if ( "${env.JOB_NAME}" == "compare_jax_vs_fortran" )
        // This command handles the email on failure feature of the jenkins test. This line is the same on every jenkins test.
      	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
