pipeline {

  agent any

  stages {
    stage('Run Column Mirror Test') {
      steps {
        sh '''
          source /etc/profile.d/larson-group.sh
          module load gcc netcdf-fortran
          ulimit -s 8388608
          python3 tests/check_mirrored_multi_col_output.py -multicol 3 -workers 2
        '''
      }
    }
  }
  post {
    failure {
      script {
        // Only the production job sends failure mail.
        if ( "${env.JOB_NAME}" == "clubb_column_mirror" ) {
          emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
        }
      }
    }
  }
}
