"""Static CLUBB budget-group definitions for the Dash budget plot."""

BUDGET_GROUPS = {
    "thlm": {
        "label": "thlm budget",
        "terms": [
            "thlm_bt",
            "thlm_ma",
            "thlm_ta",
            "thlm_mc",
            "thlm_clipping",
            "radht",
            "thlm_ls_forcing",
            "thlm_residual",
        ],
    },
    "rtm": {
        "label": "rtm budget",
        "terms": [
            "rtm_bt",
            "rtm_ma",
            "rtm_ta",
            "rtm_mc",
            "rtm_clipping",
            "rtm_pd",
            "ls_forcing",
            "rtm_residual",
        ],
    },
    "wpthlp": {
        "label": "wpthlp budget",
        "terms": [
            "wpthlp_bt",
            "wpthlp_ma",
            "wpthlp_ta",
            "wpthlp_tp",
            "wpthlp_ac",
            "wpthlp_bp",
            "wpthlp_pr1",
            "wpthlp_pr2",
            "wpthlp_pr3",
            "wpthlp_dp1",
            "wpthlp_mfl",
            "wpthlp_cl",
            "wpthlp_forcing",
            "wpthlp_residual",
        ],
    },
    "wprtp": {
        "label": "wprtp budget",
        "terms": [
            "wprtp_bt",
            "wprtp_ma",
            "wprtp_ta",
            "wprtp_tp",
            "wprtp_ac",
            "wprtp_bp",
            "wprtp_pr1",
            "wprtp_pr2",
            "wprtp_pr3",
            "wprtp_dp1",
            "wprtp_mfl",
            "wprtp_cl",
            "wprtp_pd",
            "wprtp_forcing",
            "wprtp_residual",
        ],
    },
    "wp2": {
        "label": "wp2 budget",
        "terms": [
            "wp2_bt",
            "wp2_ma",
            "wp2_ta",
            "wp2_ac",
            "wp2_bp",
            "wp2_pr1",
            "wp2_pr2",
            "wp2_pr3",
            "wp2_pr_dfsn",
            "wp2_dp1",
            "wp2_dp2",
            "wp2_cl",
            "wp2_pd",
            "wp2_splat",
            "wp2_sf",
            "wp2_residual",
        ],
    },
    "wp3": {
        "label": "wp3 budget",
        "terms": [
            "wp3_bt",
            "wp3_ma",
            "wp3_ta",
            "wp3_ac",
            "wp3_pr1",
            "wp3_pr2",
            "wp3_pr3",
            "wp3_pr_tp",
            "wp3_bp1",
            "wp3_pr_turb",
            "wp3_pr_dfsn",
            "wp3_dp1",
            "wp3_tp",
            "wp3_cl",
            "wp3_splat",
            "wp3_residual",
        ],
    },
    "thlp2": {
        "label": "thlp2 budget",
        "terms": [
            "thlp2_bt",
            "thlp2_ma",
            "thlp2_ta",
            "thlp2_tp",
            "thlp2_dp1",
            "thlp2_dp2",
            "thlp2_cl",
            "thlp2_pd",
            "thlp2_sf",
            "thlp2_forcing",
            "thlp2_residual",
        ],
    },
    "rtp2": {
        "label": "rtp2 budget",
        "terms": [
            "rtp2_bt",
            "rtp2_ma",
            "rtp2_ta",
            "rtp2_tp",
            "rtp2_dp1",
            "rtp2_dp2",
            "rtp2_cl",
            "rtp2_pd",
            "rtp2_sf",
            "rtp2_forcing",
            "rtp2_residual",
        ],
    },
    "rtpthlp": {
        "label": "rtpthlp budget",
        "terms": [
            "rtpthlp_bt",
            "rtpthlp_ma",
            "rtpthlp_ta",
            "rtpthlp_tp1",
            "rtpthlp_dp1",
            "rtpthlp_dp2",
            "rtpthlp_cl",
            "rtpthlp_tp2",
            "rtpthlp_sf",
            "rtpthlp_forcing",
            "rtpthlp_residual",
        ],
    },
    "upwp": {
        "label": "upwp budget",
        "terms": [
            "upwp_bt",
            "upwp_ma",
            "upwp_ta",
            "upwp_tp",
            "upwp_ac",
            "upwp_bp",
            "upwp_pr1",
            "upwp_pr2",
            "upwp_pr3",
            "upwp_pr4",
            "upwp_dp1",
            "upwp_cl",
            "upwp_mfl",
            "upwp_residual",
        ],
    },
    "vpwp": {
        "label": "vpwp budget",
        "terms": [
            "vpwp_bt",
            "vpwp_ma",
            "vpwp_ta",
            "vpwp_tp",
            "vpwp_ac",
            "vpwp_bp",
            "vpwp_pr1",
            "vpwp_pr2",
            "vpwp_pr3",
            "vpwp_pr4",
            "vpwp_dp1",
            "vpwp_cl",
            "vpwp_mfl",
            "vpwp_residual",
        ],
    },
    "um": {
        "label": "um budget",
        "terms": [
            "um_bt",
            "um_ma",
            "um_gf",
            "um_cf",
            "um_ta",
            "um_f",
            "um_sdmp",
            "um_ndg",
            "um_mfl",
        ],
    },
    "vm": {
        "label": "vm budget",
        "terms": [
            "vm_bt",
            "vm_ma",
            "vm_gf",
            "vm_cf",
            "vm_ta",
            "vm_f",
            "vm_sdmp",
            "vm_ndg",
            "vm_mfl",
        ],
    },
    "up2": {
        "label": "up2 budget",
        "terms": [
            "up2_bt",
            "up2_ma",
            "up2_ta",
            "up2_tp",
            "up2_dp1",
            "up2_dp2",
            "up2_pr1",
            "up2_pr2",
            "up2_sdmp",
            "up2_cl",
            "up2_pd",
            "up2_sf",
            "up2_splat",
        ],
    },
    "vp2": {
        "label": "vp2 budget",
        "terms": [
            "vp2_bt",
            "vp2_ma",
            "vp2_ta",
            "vp2_tp",
            "vp2_dp1",
            "vp2_dp2",
            "vp2_pr1",
            "vp2_pr2",
            "vp2_sdmp",
            "vp2_cl",
            "vp2_pd",
            "vp2_sf",
            "vp2_splat",
        ],
    },
    "rrm": {
        "label": "rrm budget",
        "terms": [
            "rrm_bt",
            "rrm_ma",
            "rrm_sd",
            "rrm_ta",
            "rrm_ts",
            "rrm_fill_clip",
            "rrm_mc",
            "rrm_residual",
        ],
    },
    "Nrm": {
        "label": "Nrm budget",
        "terms": [
            "Nrm_bt",
            "Nrm_ma",
            "Nrm_sd",
            "Nrm_ta",
            "Nrm_ts",
            "Nrm_cl",
            "Nrm_mc",
            "Nrm_residual",
        ],
    },
}

DEFAULT_BUDGET_GROUPS = ["thlm", "rtm", "wp2"]
