function[] = spaghetti_driver( dycoms2_time, rico_time );

%
% Rain water mixing ratio
%

% RF02

xlimits = [0., 1.45e-4];
plot_spaghetti( 'DYCOMS II RF02 rain water mixing ratio (Maximum Overlap)', ...
                'r_r [kg kg^{-1}]', 'max_overlap', 'dycoms2_rf02_ds', 'rrm', ...
                'rr', dycoms2_time, xlimits, 'dycoms2_rf02_max_rr' );

plot_spaghetti( 'DYCOMS II RF02 rain water mixing ratio (Intermediate Overlap)', ...
                'r_r [kg kg^{-1}]', 'optimal_overlap', 'dycoms2_rf02_ds', 'rrm', ...
                'rr', dycoms2_time, xlimits, 'dycoms2_rf02_opt_rr' );

plot_spaghetti( 'DYCOMS II RF02 rain water mixing ratio (Random Overlap)', ...
                'r_r [kg kg^{-1}]', 'rand_overlap', 'dycoms2_rf02_ds', 'rrm', ...
                'rr', dycoms2_time, xlimits, 'dycoms2_rf02_rand_rr' );

% RICO
xlimits = [0., 2.0e-5];
plot_spaghetti( 'RICO rain water mixing ratio (Maximum Overlap)', ...
                'r_r [kg kg^{-1}]', 'max_overlap', 'rico', 'rrm', ...
                'rr', rico_time, xlimits, 'rico_max_rr' );

plot_spaghetti( 'RICO rain water mixing ratio (Intermediate Overlap)', ...
                'r_r [kg kg^{-1}]', 'optimal_overlap', 'rico', 'rrm', ...
                'rr', rico_time, xlimits, 'rico_opt_rr' );

plot_spaghetti( 'RICO rain water mixing ratio (Random Overlap)', ...
                'r_r [kg kg^{-1}]', 'rand_overlap', 'rico', 'rrm', ...
                'rr', rico_time, xlimits, 'rico_rand_rr' );

%
% Rain droplet number concentration
%

% RF02
xlimits = [0., 4.0e5];
plot_spaghetti( 'DYCOMS II RF02 rain droplet number concentration (Maximum Overlap)', ...
                'N_r [num kg^{-1}]', 'max_overlap', 'dycoms2_rf02_ds', 'Nrm', ...
                'Nr', dycoms2_time, xlimits, 'dycoms2_rf02_max_Nr' );

plot_spaghetti( 'DYCOMS II RF02 rain droplet number concentration (Intermediate Overlap)', ...
                'N_r [num kg^{-1}]', 'optimal_overlap', 'dycoms2_rf02_ds', 'Nrm', ...
                'Nr', dycoms2_time, xlimits, 'dycoms2_rf02_opt_Nr' );

plot_spaghetti( 'DYCOMS II RF02 rain droplet number concentration (Random Overlap)', ...
                'N_r [num kg^{-1}]', 'rand_overlap', 'dycoms2_rf02_ds', 'Nrm', ...
                'Nr', dycoms2_time, xlimits, 'dycoms2_rf02_rand_Nr' );

% RICO
xlimits = [0., 4200.];
plot_spaghetti( 'RICO rain droplet number concentration (Maximum Overlap)', ...
                'N_r [num kg^{-1}]', 'max_overlap', 'rico', 'Nrm', ...
                'Nr', rico_time, xlimits, 'rico_max_Nr' );

plot_spaghetti( 'RICO rain droplet number concentration (Intermediate Overlap)', ...
                'N_r [num kg^{-1}]', 'optimal_overlap', 'rico', 'Nrm', ...
                'Nr', rico_time, xlimits, 'rico_opt_Nr' );

plot_spaghetti( 'RICO rain droplet number concentration (Random Overlap)', ...
                'N_r [num kg^{-1}]', 'rand_overlap', 'rico', 'Nrm', ...
                'Nr', rico_time, xlimits, 'rico_rand_Nr' );

%
% Vertical velocity
%

% RF02
xlimits = [-1.2, 1.2];

plot_spaghetti( 'DYCOMS II RF02 vertical velocity (Maximum Overlap)', ...
                'w [m s^{-1}]', 'max_overlap', 'dycoms2_rf02_ds', 'wm', ...
                'w', dycoms2_time, xlimits, 'dycoms2_rf02_max_w' );

plot_spaghetti( 'DYCOMS II RF02 vertical velocity (Intermediate Overlap)', ...
                'w [m s^{-1}]', 'optimal_overlap', 'dycoms2_rf02_ds', 'wm', ...
                'w', dycoms2_time, xlimits, 'dycoms2_rf02_opt_w' );

plot_spaghetti( 'DYCOMS II RF02 vertical velocity (Random Overlap)', ...
                'w [m s^{-1}]', 'rand_overlap', 'dycoms2_rf02_ds', 'wm', ...
                'w', dycoms2_time, xlimits, 'dycoms2_rf02_rand_w' );

% RICO
xlimits = [-3.0, 3.0];

plot_spaghetti( 'RICO vertical velocity (Maximum Overlap)', ...
                'w [m s^{-1}]', 'max_overlap', 'rico', 'wm', ...
                'w', rico_time, xlimits, 'rico_max_w' );

plot_spaghetti( 'RICO vertical velocity (Intermediate Overlap)', ...
                'w [m s^{-1}]', 'optimal_overlap', 'rico', 'wm', ...
                'w', rico_time, xlimits, 'rico_opt_w' );

plot_spaghetti( 'RICO vertical velocity (Random Overlap)', ...
                'w [m s^{-1}]', 'rand_overlap', 'rico', 'wm', ...
                'w', rico_time, xlimits, 'rico_rand_w' );
%
% Mellor's s
%

% RF02

xlimits = [-0.8e-3, 0.8e-3];
plot_spaghetti( 'DYCOMS II RF02 extended cloud water mixing ratio (Maximum Overlap)', ...
                's [kg kg^{-1}]', 'max_overlap', 'dycoms2_rf02_ds', 's_mellor', ...
                's_mellor', dycoms2_time, xlimits, 'dycoms2_rf02_max_s' );

plot_spaghetti( 'DYCOMS II RF02 extended cloud water mixing ratio (Intermediate Overlap)', ...
                's [kg kg^{-1}]', 'optimal_overlap', 'dycoms2_rf02_ds', 's_mellor', ...
                's_mellor', dycoms2_time, xlimits, 'dycoms2_rf02_opt_s' );

plot_spaghetti( 'DYCOMS II RF02 extended cloud water mixing ratio (Random Overlap)', ...
                's [kg kg^{-1}]', 'rand_overlap', 'dycoms2_rf02_ds', 's_mellor', ...
                's_mellor', dycoms2_time, xlimits, 'dycoms2_rf02_rand_s' );

% RICO
xlimits = [-1.0e-3, 2.5e-3];
plot_spaghetti( 'RICO extended cloud water mixing ratio (Maximum Overlap)', ...
                's [kg kg^{-1}]', 'max_overlap', 'rico', 's_mellor', ...
                's_mellor', rico_time, xlimits, 'rico_max_s' );

plot_spaghetti( 'RICO extended cloud water mixing ratio (Intermediate Overlap)', ...
                's [kg kg^{-1}]', 'optimal_overlap', 'rico', 's_mellor', ...
                's_mellor', rico_time, xlimits, 'rico_opt_s' );

plot_spaghetti( 'RICO extended cloud water mixing ratio (Random Overlap)', ...
                's [kg kg^{-1}]', 'rand_overlap', 'rico', 's_mellor', ...
                's_mellor', rico_time, xlimits, 'rico_rand_s' );

end
