pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        //Replace instances of error stop with stop (sunf95 does not support error stop)
        sh 'grep -rl "error stop" src/ | xargs sed -i "s/error stop/stop/"'
        sh 'compile/compile.bash -c config/linux_x86_64_oracle_debug.bash'
      }
    }
    stage('Run CLUBB') {
      steps {
        sh 'run_scripts/run_scm_all.bash'
      }
    }
  }
  post {
    always {
      cleanWs(cleanWhenFailure: true, cleanWhenSuccess: true, cleanWhenUnstable: true, cleanWhenAborted: true)
    }
    failure {
      emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
    }
  }
}
