pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        sh '''
          source /etc/profile.d/larson-group.sh
          module load gcc netcdf-fortran
          ./compile.py
        '''
      }
    }
    stage('Run check_budget_balance') {
      steps {
        sh '''python3 tests/check_budget_balance.py .'''
      }
    }
  }
  post {
    failure {
      script {
        // Only the production job sends failure mail.
        if ( "${env.JOB_NAME}" ==	"clubb_budget_balance" ) {
          emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
        }
      }
    }
  }
}
