pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        //Replace instances of error stop with stop (sunf95 does not support error stop)
        sh 'grep -rl "error stop" src/ | xargs sed -i "s/error stop/stop/"'
        sh 'compile/compile.bash -c config/linux_x86_64_oracle_debug.bash'
      }
    }
    stage('Run CLUBB') {
      steps {
        sh 'run_scripts/run_scm_all.bash'
      }
    }
  }
  post {
    always {
      // Certain logical functions like IF statements or TRY-CATCH blocks can only operate while in a script{} block
      script {
      // This cleans out the test workspace so the next run has a fresh start
      // However this only occurs when the test is named clubb_bin_diff_regression_backwards_compatibility_gfortran_test
      // This is to prevent the branch and copy tests from deleting thier workspaces so they are available for debugging
      if ( "${env.JOB_NAME}" == "clubb_uninit_var_oracle_test" )
      	cleanWs(cleanWhenFailure: true, cleanWhenSuccess: true, cleanWhenUnstable: true, cleanWhenAborted: true)
      }
    }
    failure {
      script {
      if ( "${env.JOB_NAME}" == "clubb_uninit_var_oracle_test" )
        // This command handles the email on failure feature of the jenkins test. This line is the same on every jenkins test.
      	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
