pipeline {
  agent any
  stages {
    stage('Enable Model Flag for Test') {
      steps {
        sh '''sed -i "s:l_test_grid_generalization.*:l_test_grid_generalization = .true.:g" src/CLUBB_core/model_flags.F90'''
        // setting l_force_descending_solves should cause results to be BFB in either ascending or descending mode, this
        // BFB criteria is enforced by `subroutine check_flipped_results` in `generalized_grid_test.F90`
        sh '''sed -i "s:l_force_descending_solves.*:l_force_descending_solves = .true.:g" src/CLUBB_core/model_flags.F90'''
      }
    }
    stage('Turn Off Sponge Damping in Case Setups') {
      steps {
        sh '''sed -i "s:thlm_sponge_damp_settings%l_sponge_damping.*:thlm_sponge_damp_settings%l_sponge_damping = .false.:g" input/case_setups/cgils_s6_model.in'''
        sh '''sed -i "s:rtm_sponge_damp_settings%l_sponge_damping.*:rtm_sponge_damp_settings%l_sponge_damping = .false.:g" input/case_setups/cgils_s6_model.in'''
        sh '''sed -i "s:thlm_sponge_damp_settings%l_sponge_damping.*:thlm_sponge_damp_settings%l_sponge_damping = .false.:g" input/case_setups/cgils_s11_model.in'''
        sh '''sed -i "s:rtm_sponge_damp_settings%l_sponge_damping.*:rtm_sponge_damp_settings%l_sponge_damping = .false.:g" input/case_setups/cgils_s11_model.in'''
        sh '''sed -i "s:thlm_sponge_damp_settings%l_sponge_damping.*:thlm_sponge_damp_settings%l_sponge_damping = .false.:g" input/case_setups/cgils_s12_model.in'''
        sh '''sed -i "s:rtm_sponge_damp_settings%l_sponge_damping.*:rtm_sponge_damp_settings%l_sponge_damping = .false.:g" input/case_setups/cgils_s12_model.in'''
      }
    }
    stage('Compile') {
      // we need -O0 for this test to be BFB, which is added when using debug flags
      steps {
        sh '''source /etc/profile.d/larson-group.sh
              module load intel netcdf-fortran
              ./compile.py -debug'''
      }
    }
    stage('Run') {
      steps {
        sh '''python3 run_scripts/run_clubb_w_varying_flags.py -f run_scripts/run_bindiff_w_flags_config_host_flags.json'''
      }
    }
  }
  post {
    always {
      // Certain logical functions like IF statements or TRY-CATCH blocks can only operate while in a script{} block
      script {
      // This cleans out the test workspace so the next run has a fresh start
      // However this only occurs when the test is named clubb_generalized_vert_grid_host_flags
      // This is to prevent the branch and copy tests from deleting thier workspaces so they are available for debugging
      if ( "${env.JOB_NAME}" == "clubb_generalized_vert_grid_host_flags" )
      	cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenSuccess: true, cleanWhenUnstable: true)
      }
    }
    failure {
      script {
      if ( "${env.JOB_NAME}" == "clubb_generalized_vert_grid_host_flags" )
        // This command handles the email on failure feature of the jenkins test. This line is the same on every jenkins test.
      	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
