% $Id$
function [ wp2_clubb_pdf, wp3_clubb_pdf, ...
           rtp2_clubb_pdf, rtp3_clubb_pdf, ...
           thlp2_clubb_pdf, thlp3_clubb_pdf, ...
           Skw_clubb_pdf, Skrt_clubb_pdf, ...
           Skthl_clubb_pdf, precip_frac_clubb, ...
           rrm_clubb_pdf, rrp2_clubb_pdf, ...
           rrp3_clubb_pdf, Skrr_clubb_pdf, ...
           rrm_ip_clubb_pdf, rrp2_ip_clubb_pdf, ...
           rrp3_ip_clubb_pdf, Skrr_ip_clubb_pdf, ...
           voms_ip_rr_clubb_pdf, mean_lnrr_clubb_pdf, ...
           lnrrp2_clubb_pdf, lnrrp3_clubb_pdf, ...
           Sk_lnrr_clubb_pdf, ...
           Nrm_clubb_pdf, Nrp2_clubb_pdf, ...
           Nrp3_clubb_pdf, SkNr_clubb_pdf, ...
           Nrm_ip_clubb_pdf, Nrp2_ip_clubb_pdf, ...
           Nrp3_ip_clubb_pdf, SkNr_ip_clubb_pdf, ...
           voms_ip_Nr_clubb_pdf, mean_lnNr_clubb_pdf, ...
           lnNrp2_clubb_pdf, lnNrp3_clubb_pdf, ...
           Sk_lnNr_clubb_pdf ] ...
= calc_stats_CLUBB( mu_w_1, mu_w_2, ...
                    mu_rt_1, mu_rt_2, ...
                    mu_thl_1, mu_thl_2, ...
                    mu_rr_1_n, mu_rr_2_n, ...
                    mu_Nr_1_n, mu_Nr_2_n, ...
                    sigma_w_1, sigma_w_2, ...
                    sigma_rt_1, sigma_rt_2, ...
                    sigma_thl_1, sigma_thl_2, ...
                    sigma_rr_1_n, sigma_rr_2_n, ...
                    sigma_Nr_1_n, sigma_Nr_2_n, ...
                    mixt_frac, precip_frac_1, ...
                    precip_frac_2 )

% Calculations based on CLUBB PDF parameters.
wm   = mixt_frac * mu_w_1   + ( 1.0 - mixt_frac ) * mu_w_2;
rtm  = mixt_frac * mu_rt_1  + ( 1.0 - mixt_frac ) * mu_rt_2;
thlm = mixt_frac * mu_thl_1 + ( 1.0 - mixt_frac ) * mu_thl_2;
wp2_clubb_pdf ...
= mixt_frac * ( ( mu_w_1 - wm )^2 + sigma_w_1^2 ) ...
  + ( 1.0 - mixt_frac ) * ( ( mu_w_2 - wm )^2 + sigma_w_2^2 );
rtp2_clubb_pdf ...
= mixt_frac * ( ( mu_rt_1 - rtm )^2 + sigma_rt_1^2 ) ...
  + ( 1.0 - mixt_frac ) * ( ( mu_rt_2 - rtm )^2 + sigma_rt_2^2 );
thlp2_clubb_pdf ...
= mixt_frac * ( ( mu_thl_1 - thlm )^2 + sigma_thl_1^2 ) ...
  + ( 1.0 - mixt_frac ) * ( ( mu_thl_2 - thlm )^2 + sigma_thl_2^2 );
wp3_clubb_pdf ...
= mixt_frac * ( mu_w_1 - wm ) ...
            * ( ( mu_w_1 - wm )^2 + 3.0*sigma_w_1^2 ) ...
  + ( 1.0 - mixt_frac ) * ( mu_w_2 - wm ) ...
                        * ( ( mu_w_2 - wm )^2 + 3.0*sigma_w_2^2 );
rtp3_clubb_pdf ...
= mixt_frac * ( mu_rt_1 - rtm ) ...
            * ( ( mu_rt_1 - rtm )^2 + 3.0*sigma_rt_1^2 ) ...
  + ( 1.0 - mixt_frac ) * ( mu_rt_2 - rtm ) ...
                        * ( ( mu_rt_2 - rtm )^2 + 3.0*sigma_rt_2^2 );
thlp3_clubb_pdf ...
= mixt_frac * ( mu_thl_1 - thlm ) ...
            * ( ( mu_thl_1 - thlm )^2 + 3.0*sigma_thl_1^2 ) ...
  + ( 1.0 - mixt_frac ) * ( mu_thl_2 - thlm ) ...
                        * ( ( mu_thl_2 - thlm )^2 + 3.0*sigma_thl_2^2 );

Skw_clubb_pdf   = wp3_clubb_pdf   / wp2_clubb_pdf^1.5;
Skrt_clubb_pdf  = rtp3_clubb_pdf  / rtp2_clubb_pdf^1.5;
Skthl_clubb_pdf = thlp3_clubb_pdf / thlp2_clubb_pdf^1.5;

% Calculations for hydrometeor fields based on CLUBB PDF parameters.
rrm_clubb_pdf = mixt_frac * precip_frac_1 ...
                * exp( mu_rr_1_n + 0.5 * sigma_rr_1_n^2 ) ...
                + ( 1.0 - mixt_frac ) * precip_frac_2 ...
                  * exp( mu_rr_2_n + 0.5 * sigma_rr_2_n^2 );
Nrm_clubb_pdf = mixt_frac * precip_frac_1 ...
                * exp( mu_Nr_1_n + 0.5 * sigma_Nr_1_n^2 ) ...
                + ( 1.0 - mixt_frac ) * precip_frac_2 ...
                  * exp( mu_Nr_2_n + 0.5 * sigma_Nr_2_n^2 );
rrp2_clubb_pdf = mixt_frac * precip_frac_1 ...
                 * exp( 2.0 * mu_rr_1_n + 2.0 * sigma_rr_1_n^2 ) ...
                 + ( 1.0 - mixt_frac ) * precip_frac_2 ...
                   * exp( 2.0 * mu_rr_2_n + 2.0 * sigma_rr_2_n^2 ) ...
                 - rrm_clubb_pdf^2;
Nrp2_clubb_pdf = mixt_frac * precip_frac_1 ...
                 * exp( 2.0 * mu_Nr_1_n + 2.0 * sigma_Nr_1_n^2 ) ...
                 + ( 1.0 - mixt_frac ) * precip_frac_2 ...
                   * exp( 2.0 * mu_Nr_2_n + 2.0 * sigma_Nr_2_n^2 ) ...
                 - Nrm_clubb_pdf^2;
rrp3_clubb_pdf = mixt_frac * precip_frac_1 ...
                 * exp( 3.0 * mu_rr_1_n + 4.5 * sigma_rr_1_n^2 ) ...
                 + ( 1.0 - mixt_frac ) * precip_frac_2 ...
                   * exp( 3.0 * mu_rr_2_n + 4.5 * sigma_rr_2_n^2 ) ...
                 - 3.0 * rrp2_clubb_pdf * rrm_clubb_pdf ...
                 - rrm_clubb_pdf^3;
Nrp3_clubb_pdf = mixt_frac * precip_frac_1 ...
                 * exp( 3.0 * mu_Nr_1_n + 4.5 * sigma_Nr_1_n^2 ) ...
                 + ( 1.0 - mixt_frac ) * precip_frac_2 ...
                   * exp( 3.0 * mu_Nr_2_n + 4.5 * sigma_Nr_2_n^2 ) ...
                 - 3.0 * Nrp2_clubb_pdf * Nrm_clubb_pdf ...
                 - Nrm_clubb_pdf^3;

Skrr_clubb_pdf = rrp3_clubb_pdf / rrp2_clubb_pdf^1.5;
SkNr_clubb_pdf = Nrp3_clubb_pdf / Nrp2_clubb_pdf^1.5;

precip_frac_clubb = mixt_frac * precip_frac_1 ...
                    + ( 1.0 - mixt_frac ) * precip_frac_2;

if ( rrm_clubb_pdf > 0.0 )
   % Rain water mixing ratio is found at this level in CLUBB.
   [ rrm_ip_clubb_pdf, rrp2_ip_clubb_pdf, ...
     rrp3_ip_clubb_pdf, Skrr_ip_clubb_pdf ] ...
   = calc_in_precip_values( rrm_clubb_pdf, rrp2_clubb_pdf, ...
                            rrp3_clubb_pdf, precip_frac_clubb );
   % Calculate in-precip variance-over-mean-squared for rr.
   voms_ip_rr_clubb_pdf = rrp2_ip_clubb_pdf / rrm_ip_clubb_pdf^2;
else
   % Set values to 0.
   rrm_ip_clubb_pdf = 0.0;
   rrp2_ip_clubb_pdf = 0.0;
   rrp3_ip_clubb_pdf = 0.0;
   Skrr_ip_clubb_pdf = 0.0;
   voms_ip_rr_clubb_pdf = 0.0;
end

if ( Nrm_clubb_pdf > 0.0 )
   % Rain drop concentration is found at this level in CLUBB.
   [ Nrm_ip_clubb_pdf, Nrp2_ip_clubb_pdf, ...
     Nrp3_ip_clubb_pdf, SkNr_ip_clubb_pdf ] ...
   = calc_in_precip_values( Nrm_clubb_pdf, Nrp2_clubb_pdf, ...
                            Nrp3_clubb_pdf, precip_frac_clubb );
   % Calculate in-precip variance-over-mean-squared for Nr.
   voms_ip_Nr_clubb_pdf = Nrp2_ip_clubb_pdf / Nrm_ip_clubb_pdf^2;
else
   % Set values to 0.
   Nrm_ip_clubb_pdf = 0.0;
   Nrp2_ip_clubb_pdf = 0.0;
   Nrp3_ip_clubb_pdf = 0.0;
   SkNr_ip_clubb_pdf = 0.0;
   voms_ip_Nr_clubb_pdf = 0.0;
end

% Calculate the mean, variance, 3rd-order central moment, and skewness of
% ln rr for all rr in precip. (where rr > 0) for CLUBB.
if ( mu_rr_1_n > -realmax('single') && mu_rr_2_n > -realmax('single') )

   mean_lnrr_clubb_pdf ...
   = mixt_frac * ( precip_frac_1 / precip_frac_clubb ) * mu_rr_1_n ...
     + ( 1.0 - mixt_frac ) ...
       * ( precip_frac_2 / precip_frac_clubb ) * mu_rr_2_n;

   lnrrp2_clubb_pdf ...
   = mixt_frac * ( precip_frac_1 / precip_frac_clubb ) ...
     * ( ( mu_rr_1_n - mean_lnrr_clubb_pdf )^2 + sigma_rr_1_n^2 ) ...
     + ( 1.0 - mixt_frac ) * ( precip_frac_2 / precip_frac_clubb ) ...
       * ( ( mu_rr_2_n - mean_lnrr_clubb_pdf )^2 + sigma_rr_2_n^2 );

   lnrrp3_clubb_pdf ...
   = mixt_frac * ( precip_frac_1 / precip_frac_clubb ) ...
     * ( ( mu_rr_1_n - mean_lnrr_clubb_pdf )^3 ...
         + 3.0 * ( mu_rr_1_n - mean_lnrr_clubb_pdf ) * sigma_rr_1_n^2 ) ...
     + ( 1.0 - mixt_frac ) * ( precip_frac_2 / precip_frac_clubb ) ...
       * ( ( mu_rr_2_n - mean_lnrr_clubb_pdf )^3 ...
           + 3.0 * ( mu_rr_2_n - mean_lnrr_clubb_pdf ) * sigma_rr_2_n^2 );

   Sk_lnrr_clubb_pdf = lnrrp3_clubb_pdf / lnrrp2_clubb_pdf^1.5;

elseif ( mu_rr_1_n > -realmax('single') )

   mean_lnrr_clubb_pdf ...
   = mixt_frac * ( precip_frac_1 / precip_frac_clubb ) * mu_rr_1_n;

   lnrrp2_clubb_pdf ...
   = mixt_frac * ( precip_frac_1 / precip_frac_clubb ) ...
     * ( ( mu_rr_1_n - mean_lnrr_clubb_pdf )^2 + sigma_rr_1_n^2 );

   lnrrp3_clubb_pdf ...
   = mixt_frac * ( precip_frac_1 / precip_frac_clubb ) ...
     * ( ( mu_rr_1_n - mean_lnrr_clubb_pdf )^3 ...
         + 3.0 * ( mu_rr_1_n - mean_lnrr_clubb_pdf ) * sigma_rr_1_n^2 );

   Sk_lnrr_clubb_pdf = lnrrp3_clubb_pdf / lnrrp2_clubb_pdf^1.5;

elseif ( mu_rr_2_n > -realmax('single') )

   mean_lnrr_clubb_pdf ...
   = ( 1.0 - mixt_frac ) ...
     * ( precip_frac_2 / precip_frac_clubb ) * mu_rr_2_n;

   lnrrp2_clubb_pdf ...
   = ( 1.0 - mixt_frac ) * ( precip_frac_2 / precip_frac_clubb ) ...
     * ( ( mu_rr_2_n - mean_lnrr_clubb_pdf )^2 + sigma_rr_2_n^2 );

   lnrrp3_clubb_pdf ...
   = ( 1.0 - mixt_frac ) * ( precip_frac_2 / precip_frac_clubb ) ...
     * ( ( mu_rr_2_n - mean_lnrr_clubb_pdf )^3 ...
         + 3.0 * ( mu_rr_2_n - mean_lnrr_clubb_pdf ) * sigma_rr_2_n^2 );

   Sk_lnrr_clubb_pdf = lnrrp3_clubb_pdf / lnrrp2_clubb_pdf^1.5;

else

   mean_lnrr_clubb_pdf = -realmax('single');
   lnrrp2_clubb_pdf = 0.0;
   lnrrp3_clubb_pdf = 0.0;
   Sk_lnrr_clubb_pdf = 0.0;

end

if ( mu_Nr_1_n > -realmax('single') && mu_Nr_2_n > -realmax('single') )

   mean_lnNr_clubb_pdf ...
   = mixt_frac * ( precip_frac_1 / precip_frac_clubb ) * mu_Nr_1_n ...
     + ( 1.0 - mixt_frac ) ...
       * ( precip_frac_2 / precip_frac_clubb ) * mu_Nr_2_n;

   lnNrp2_clubb_pdf ...
   = mixt_frac * ( precip_frac_1 / precip_frac_clubb ) ...
     * ( ( mu_Nr_1_n - mean_lnNr_clubb_pdf )^2 + sigma_Nr_1_n^2 ) ...
     + ( 1.0 - mixt_frac ) * ( precip_frac_2 / precip_frac_clubb ) ...
       * ( ( mu_Nr_2_n - mean_lnNr_clubb_pdf )^2 + sigma_Nr_2_n^2 );

   lnNrp3_clubb_pdf ...
   = mixt_frac * ( precip_frac_1 / precip_frac_clubb ) ...
     * ( ( mu_Nr_1_n - mean_lnNr_clubb_pdf )^3 ...
         + 3.0 * ( mu_Nr_1_n - mean_lnNr_clubb_pdf ) * sigma_Nr_1_n^2 ) ...
     + ( 1.0 - mixt_frac ) * ( precip_frac_2 / precip_frac_clubb ) ...
       * ( ( mu_Nr_2_n - mean_lnNr_clubb_pdf )^3 ...
           + 3.0 * ( mu_Nr_2_n - mean_lnNr_clubb_pdf ) * sigma_Nr_2_n^2 );

   Sk_lnNr_clubb_pdf = lnNrp3_clubb_pdf / lnNrp2_clubb_pdf^1.5;

elseif ( mu_Nr_1_n > -realmax('single') )

   mean_lnNr_clubb_pdf ...
   = mixt_frac * ( precip_frac_1 / precip_frac_clubb ) * mu_Nr_1_n;

   lnNrp2_clubb_pdf ...
   = mixt_frac * ( precip_frac_1 / precip_frac_clubb ) ...
     * ( ( mu_Nr_1_n - mean_lnNr_clubb_pdf )^2 + sigma_Nr_1_n^2 );

   lnNrp3_clubb_pdf ...
   = mixt_frac * ( precip_frac_1 / precip_frac_clubb ) ...
     * ( ( mu_Nr_1_n - mean_lnNr_clubb_pdf )^3 ...
         + 3.0 * ( mu_Nr_1_n - mean_lnNr_clubb_pdf ) * sigma_Nr_1_n^2 );

   Sk_lnNr_clubb_pdf = lnNrp3_clubb_pdf / lnNrp2_clubb_pdf^1.5;

elseif ( mu_Nr_2_n > -realmax('single') )

   mean_lnNr_clubb_pdf ...
   = ( 1.0 - mixt_frac ) ...
     * ( precip_frac_2 / precip_frac_clubb ) * mu_Nr_2_n;

   lnNrp2_clubb_pdf ...
   = ( 1.0 - mixt_frac ) * ( precip_frac_2 / precip_frac_clubb ) ...
     * ( ( mu_Nr_2_n - mean_lnNr_clubb_pdf )^2 + sigma_Nr_2_n^2 );

   lnNrp3_clubb_pdf ...
   = ( 1.0 - mixt_frac ) * ( precip_frac_2 / precip_frac_clubb ) ...
     * ( ( mu_Nr_2_n - mean_lnNr_clubb_pdf )^3 ...
         + 3.0 * ( mu_Nr_2_n - mean_lnNr_clubb_pdf ) * sigma_Nr_2_n^2 );

   Sk_lnNr_clubb_pdf = lnNrp3_clubb_pdf / lnNrp2_clubb_pdf^1.5;

else

   mean_lnNr_clubb_pdf = -realmax('single');
   lnNrp2_clubb_pdf = 0.0;
   lnNrp3_clubb_pdf = 0.0;
   Sk_lnNr_clubb_pdf = 0.0;

end
