pipeline {

  // OpenMP GPU offloading needs compute capability > 70, which currently only carson has
  agent { label 'carson' }
  
  stages {
    stage('Modify Config Flags') {
      steps {
        sh '''sed -i "s:penta_solve_method.*:penta_solve_method = 2:g" input/tunable_parameters/configurable_model_flags.in'''
        sh '''sed -i "s:tridiag_solve_method.*:tridiag_solve_method = 2:g" input/tunable_parameters/configurable_model_flags.in'''
        sh '''sed -i "s:lh_straight_mc.*:lh_straight_mc = true:g" input/tunable_parameters/configurable_model_flags.in'''
        sh '''sed -i "s:set(GPU_DEFINITIONS CLUBB_GPU CUDA):set(GPU_DEFINITIONS CLUBB_GPU):g" cmake/toolchains/linux_x86_64_nvfortran.cmake'''
        sh '''run_scripts/create_multi_col_params.py -n 32 -param_file input/tunable_parameters/tunable_parameters.in -mode dup_tweak'''
      }
    }
    stage('Compile CPU') {
      steps {
        sh '''source /etc/profile.d/larson-group.sh
              module load nvhpc netcdf-fortran
              ./compile.py'''
      }
    }
    stage('Run CPU') {
      steps {
        sh '''ulimit -s 8388608
              run_scripts/run_scm.py -params clubb_params_multi_col.in -stats input/stats/multi_col_stats.in -debug 0 arm
              run_scripts/run_scm.py -params clubb_params_multi_col.in -stats input/stats/multi_col_stats.in -debug 0 -max_iters 500 cobra
              run_scripts/run_scm.py -params clubb_params_multi_col.in -stats input/stats/multi_col_stats.in -debug 0 -max_iters 10 rico_silhs
              mv output cpu_output; mkdir output'''
      }
    }
    stage('Compile GPU_ACC') {
      steps {
          sh ''' source /etc/profile.d/larson-group.sh
                 module load nvhpc netcdf-fortran
                 ./compile.py -gpu openacc'''
      }
    }
    stage('Run GPU_ACC') {
      steps {
        lock( "GPU_${env.NODE_NAME}" ) {
          sh '''ulimit -s 8388608
                run_scripts/run_scm.py -params clubb_params_multi_col.in -stats input/stats/multi_col_stats.in -debug 0 arm
                run_scripts/run_scm.py -params clubb_params_multi_col.in -stats input/stats/multi_col_stats.in -debug 0 -max_iters 500 cobra
                run_scripts/run_scm.py -params clubb_params_multi_col.in -stats input/stats/multi_col_stats.in -debug 0 -max_iters 10 rico_silhs
                mv output acc_output; mkdir output'''
        }
      }
    }
    stage('Compile GPU_OMP') {
      steps {
        sh '''source /etc/profile.d/larson-group.sh
              module load nvhpc netcdf-fortran
              compile/convert_acc_to_omp.bash
              ./compile.py -gpu openmp'''
      }
    }
    stage('Run GPU_OMP') {
      steps {
        lock( "GPU_${env.NODE_NAME}" ) {
          sh '''ulimit -s 8388608
                run_scripts/run_scm.py -params clubb_params_multi_col.in -stats input/stats/multi_col_stats.in -debug 0 arm
                run_scripts/run_scm.py -params clubb_params_multi_col.in -stats input/stats/multi_col_stats.in -debug 0 -max_iters 500 cobra
                run_scripts/run_scm.py -params clubb_params_multi_col.in -stats input/stats/multi_col_stats.in -debug 0 -max_iters 10 rico_silhs
                mv output omp_output; mkdir output'''
        }
      }
    }
    stage('Compare CPU vs ACC') {
      steps {
        sh '''run_scripts/run_bindiff_all.py -v 2 -t 1e-6 -s cpu_output acc_output'''
      }
    }
    stage('Compare CPU vs OMP') {
      steps {
        sh '''run_scripts/run_bindiff_all.py -v 2 -t 1e-6 -s cpu_output omp_output'''
      }
    }
  }
  post {
    failure {
      script {
      if ( "${env.JOB_NAME}" == "clubb_nvhpc_gpu_vs_cpu_diffness" )
        // This command handles the email on failure feature of the jenkins test. This line is the same on every jenkins test.
      	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
