% $Id$
function [ mu_w_1, mu_w_2, ...
           mu_rt_1, mu_rt_2, ...
           mu_thl_1, mu_thl_2, ...
           mu_chi_1, mu_chi_2, ...
           mu_eta_1, mu_eta_2, ...
           mu_rr_1_n, mu_rr_2_n, ...
           mu_Nr_1_n, mu_Nr_2_n, ...
           sigma_w_1, sigma_w_2, ...
           sigma_rt_1, sigma_rt_2, ...
           sigma_thl_1, sigma_thl_2, ...
           sigma_chi_1, sigma_chi_2, ...
           sigma_eta_1, sigma_eta_2, ...
           sigma_rr_1_n, sigma_rr_2_n, ...
           sigma_Nr_1_n, sigma_Nr_2_n, ...
           mixt_frac, precip_frac_1, ...
           precip_frac_2 ] ...
= unpack_CLUBB_vars_fit_tests( var_clubb, clubb_height_idx, ...
                               clubb_time_idx )

% CLUBB variables indices
global idx_w_1
global idx_w_2
global idx_rt_1
global idx_rt_2
global idx_thl_1
global idx_thl_2
global idx_chi_1
global idx_chi_2
global idx_mu_rr_1_n
global idx_mu_rr_2_n
global idx_mu_Nr_1_n
global idx_mu_Nr_2_n
global idx_varnce_w_1
global idx_varnce_w_2
global idx_varnce_rt_1
global idx_varnce_rt_2
global idx_varnce_thl_1
global idx_varnce_thl_2
global idx_stdev_chi_1
global idx_stdev_chi_2
global idx_stdev_eta_1
global idx_stdev_eta_2
global idx_sigma_rr_1_n
global idx_sigma_rr_2_n
global idx_sigma_Nr_1_n
global idx_sigma_Nr_2_n
global idx_mixt_frac
global idx_precip_frac_1
global idx_precip_frac_2

% PDF component means.
mu_w_1 = var_clubb( idx_w_1, 1, 1, clubb_height_idx, clubb_time_idx );
mu_w_2 = var_clubb( idx_w_2, 1, 1, clubb_height_idx, clubb_time_idx );
mu_rt_1 = var_clubb( idx_rt_1, 1, 1, clubb_height_idx, clubb_time_idx );
mu_rt_2 = var_clubb( idx_rt_2, 1, 1, clubb_height_idx, clubb_time_idx );
mu_thl_1 = var_clubb( idx_thl_1, 1, 1, clubb_height_idx, clubb_time_idx );
mu_thl_2 = var_clubb( idx_thl_2, 1, 1, clubb_height_idx, clubb_time_idx );
mu_chi_1 = var_clubb( idx_chi_1, 1, 1, clubb_height_idx, clubb_time_idx );
mu_chi_2 = var_clubb( idx_chi_2, 1, 1, clubb_height_idx, clubb_time_idx );
mu_eta_1 = 0.0; % The component mean of eta is always defined as 0.
mu_eta_2 = 0.0; % The component mean of eta is always defined as 0.
mu_rr_1_n = var_clubb( idx_mu_rr_1_n, 1, 1, ...
                       clubb_height_idx, clubb_time_idx );
mu_rr_2_n = var_clubb( idx_mu_rr_2_n, 1, 1, ...
                       clubb_height_idx, clubb_time_idx );
mu_Nr_1_n = var_clubb( idx_mu_Nr_1_n, 1, 1, ...
                       clubb_height_idx, clubb_time_idx );
mu_Nr_2_n = var_clubb( idx_mu_Nr_2_n, 1, 1, ...
                       clubb_height_idx, clubb_time_idx );

% PDF component standard deviations.
sigma_w_1 = sqrt( var_clubb( idx_varnce_w_1, 1, 1, ...
                             clubb_height_idx, clubb_time_idx ) );
sigma_w_2 = sqrt( var_clubb( idx_varnce_w_2, 1, 1, ...
                             clubb_height_idx, clubb_time_idx ) );
sigma_rt_1 = sqrt( var_clubb( idx_varnce_rt_1, 1, 1, ...
                              clubb_height_idx, clubb_time_idx ) );
sigma_rt_2 = sqrt( var_clubb( idx_varnce_rt_2, 1, 1, ...
                              clubb_height_idx, clubb_time_idx ) );
sigma_thl_1 = sqrt( var_clubb( idx_varnce_thl_1, 1, 1, ...
                               clubb_height_idx, clubb_time_idx ) );
sigma_thl_2 = sqrt( var_clubb( idx_varnce_thl_2, 1, 1, ...
                               clubb_height_idx, clubb_time_idx ) );
sigma_chi_1 = var_clubb( idx_stdev_chi_1, 1, 1, ...
                         clubb_height_idx, clubb_time_idx );
sigma_chi_2 = var_clubb( idx_stdev_chi_2, 1, 1, ...
                         clubb_height_idx, clubb_time_idx );
sigma_eta_1 = var_clubb( idx_stdev_eta_1, 1, 1, ...
                         clubb_height_idx, clubb_time_idx );
sigma_eta_2 = var_clubb( idx_stdev_eta_2, 1, 1, ...
                         clubb_height_idx, clubb_time_idx );
sigma_rr_1_n = var_clubb( idx_sigma_rr_1_n, 1, 1, ...
                          clubb_height_idx, clubb_time_idx );
sigma_rr_2_n = var_clubb( idx_sigma_rr_2_n, 1, 1, ...
                          clubb_height_idx, clubb_time_idx );
sigma_Nr_1_n = var_clubb( idx_sigma_Nr_1_n, 1, 1, ...
                          clubb_height_idx, clubb_time_idx );
sigma_Nr_2_n = var_clubb( idx_sigma_Nr_2_n, 1, 1, ...
                          clubb_height_idx, clubb_time_idx );

% Other variables involved in the PDF.
mixt_frac = var_clubb( idx_mixt_frac, 1, 1, ...
                       clubb_height_idx, clubb_time_idx );
precip_frac_1 = var_clubb( idx_precip_frac_1, 1, 1, ...
                           clubb_height_idx, clubb_time_idx );
precip_frac_2 = var_clubb( idx_precip_frac_2, 1, 1, ...
                           clubb_height_idx, clubb_time_idx );
