pipeline {
  agent any
  stages {
    stage('Checkout Clubb_Release') {
      steps {
        sh '''git clone https://github.com/larson-group/clubb_release.git'''
      }
    }
    stage('Compile Clubb Release ') {
      steps {
        sh 'clubb_release/compile/compile.bash -c config/linux_x86_64_ifort.bash'
      }
    }
    stage('Run') {
      steps {
        sh '''source /opt/intel/bin/ifortvars.sh intel64
              clubb_release/run_scripts/run_scm_all.bash'''
      }
    }
  }
  post {
    always {
      script {
      if ( "${env.JOB_NAME}" == "clubb_release_intel_build" )
      	cleanWs(cleanWhenFailure: true, cleanWhenSuccess: true, cleanWhenUnstable: true, cleanWhenAborted: true)
      }
    }
    failure {
      script {
      if ( "${env.JOB_NAME}" == "clubb_release_intel_build" )
      	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
