pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        sh '''compile/compile.bash -c config/linux_x86_64_gfortran.bash'''
      }
    }
    stage('Run') {
      steps {
        sh '''run_scripts/run_scm_all.bash'''
      }
    }
  }
  post {
    always {
      cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenSuccess: true, cleanWhenUnstable: true)
    }
  }
}
