pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        sh '''
          source /etc/profile.d/larson-group.sh
          module load nvhpc netcdf-fortran
          ./compile.py -precision single
        '''
      }
    }
    stage('Run') {
      steps {
        sh '''run_scripts/run_scm_all.py -nproc 4'''
      }
    }
  }
  post {
    failure {
      script {
        // Only the production job sends failure mail.
        if ( "${env.JOB_NAME}" == "clubb_single_prec_build" ) {
          emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
        }
      }
    }
  }
}
