pipeline {
  agent any
  stages {
    stage('Clone SysAdmin to tmp') {
      steps {
        // This clones the sys_admin repo to use later in the test
        sh '''rm -rf /home/jenkins/clubb_bit_diff_e3sm_flags_gfortran_workspace/sys_admin
              git clone https://github.com/larson-group/sys_admin.git /home/jenkins/clubb_bit_diff_e3sm_flags_gfortran_workspace/sys_admin'''
      }
    }
    stage('Run Python Test') {
      steps {
        // Here we run the run_test.py script with the correct config, both are found in the sys_admin repo
        sh '''python3 /home/jenkins/clubb_bit_diff_e3sm_flags_gfortran_workspace/sys_admin/python_nightly_test_suite/run_test.py -c /home/jenkins/clubb_bit_diff_e3sm_flags_gfortran_workspace/bit_diff_clubb_e3sm_flags_config'''
      }
    }
  }
  post {
    always {
      // Certain logical functions like IF statements or TRY-CATCH blocks can only operate while in a script{} block
      script {
      // This cleans out the test workspace so the next run has a fresh start
      // However this only occurs when the test is named clubb_bit_diff_e3sm_flags_gfortran
      // This is to prevent the branch and copy tests from deleting thier workspaces so they are available for debugging
      if ( "${env.JOB_NAME}" == "clubb_bit_diff_e3sm_flags_gfortran" )
      	cleanWs(cleanWhenSuccess: true, cleanWhenFailure: true)
      }
    }
    failure {
      script {
      if ( "${env.JOB_NAME}" ==	"clubb_bit_diff_e3sm_flags_gfortran" )
        // This command handles the email on failure feature of the jenkins test. This line is the same on every jenkins test.
      	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
