pipeline {

  agent any

  stages {
    stage('Run Column Mirror Test') {
      steps {
        sh '''source /etc/profile.d/larson-group.sh
              module load gcc netcdf-fortran
              ulimit -s 8388608
              python3 tests/check_mirrored_multi_col_output.py -n 3 -nproc 2'''
      }
    }
  }
  post {
    failure {
      script {
      if ( "${env.JOB_NAME}" == "clubb_column_mirror_test" )
        // This command handles the email on failure feature of the jenkins test. This line is the same on every jenkins test.
        emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
