pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        sh '''sed -r 's/-ffpe-trap=(\\w,?)+\\s//g' -i clubb/compile/config/linux_x86_64_gfortran.bash
              clubb/compile/compile.bash'''
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'sys_admin']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'Generic_Key', url: 'https://github.com/larson-group/sys_admin']]])
      }
    }
    stage('Run fire_tuner') {
      steps {
        sh '''sys_admin/bitten_test_driver_scripts/fire_tuner.bash ./clubb'''
      }
    }
  }
  post {
    always {
      cleanWs(cleanWhenFailure: true, cleanWhenSuccess: true, cleanWhenUnstable: true)
    }
    failure {
      emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
    }
  }
}
