pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        sh '''sed -r 's/-ffpe-trap=(\\w,?)+\\s//g' -i clubb/compile/config/linux_x86_64_gfortran.bash
              clubb/compile/compile.bash'''
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'sys_admin']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'Generic_Key', url: 'https://github.com/larson-group/sys_admin']]])
      }
    }
    stage('Run fire_tuner') {
      steps {
        sh '''sys_admin/bitten_test_driver_scripts/fire_tuner.bash ./clubb'''
      }
    }
  }
  post {
    always {
      cleanWs(cleanWhenFailure: true, cleanWhenSuccess: true, cleanWhenUnstable: true)
    }
  }
}
