pipeline {

  agent any
  
  stages {
    stage('Run test_monoflux_limiter_GPU.py') {
      steps {
        lock( "GPU_${env.NODE_NAME}" ) {
          sh '''source /etc/profile.d/larson-group.sh
                module load nvhpc netcdf-fortran
                python tests/test_monoflux_limiter_GPU.py'''
        }
      }
    }
  }
  post {
    failure {
      script {
      if ( "${env.JOB_NAME}" ==	"clubb_monoflux_CPU_vs_GPU_diff" )
        // This command handles the email on failure feature of the jenkins test. This line is the same on every jenkins test.
      	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
