pipeline {
  agent any
  stages {
    stage('Clone SysAdmin to tmp') {
      steps {
        sh '''rm -rf /home/jenkins/clubb_bin_diff_regression_backwards_compatibility_gfortran_test_workspace/sys_admin
              git clone https://github.com/larson-group/sys_admin.git /home/jenkins/clubb_bin_diff_regression_backwards_compatibility_gfortran_test_workspace/sys_admin'''
      }
    }
    stage('Run Python Test') {
      steps {
        sh '''python3 /home/jenkins/clubb_bin_diff_regression_backwards_compatibility_gfortran_test_workspace/sys_admin/python_nightly_test_suite/run_test.py -c /home/jenkins/clubb_bin_diff_regression_backwards_compatibility_gfortran_test_workspace/bit_diff_clubb_config'''
      }
    }
  }
  post {
    always {
      script {
      if ( "${env.JOB_NAME}" == "clubb_bin_diff_regression_backwards_compatibility_gfortran_test" )
      	cleanWs(cleanWhenSuccess: true, cleanWhenFailure: true)
      }
    }
    failure {
      script {
      if ( "${env.JOB_NAME}" ==	"clubb_bin_diff_regression_backwards_compatibility_gfortran_test" )
      	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
