pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        // This command is directly modifying flags present in the compile configuration, these changes will linger after the test if the file is not reset
        sh '''
          source /etc/profile.d/larson-group.sh
          module load gcc netcdf-fortran
          ./compile.py
        '''
      }
    }
    stage('Run test_fire_tuner') {
      steps {
        sh '''python3 tests/test_fire_tuner.py .'''
      }
    }
  }
  post {
    failure {
      script {
        // Only the production job sends failure mail.
        if ( "${env.JOB_NAME}" ==	"clubb_fire_tuning" ) {
          emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
        }
      }
    }
  }
}
