pipeline {
  agent any
  stages {
    stage('Compile') {
      steps {
        sh 'compile/compile.bash -c config/linux_x86_64_gfortran.bash'
      }
    }
    stage('Run SILHS test script') {
      steps {
        sh 'run_scripts/run_silhs_test.bash'
      }
    }
  }
  post {
    always {
      cleanWs(cleanWhenFailure: true, cleanWhenSuccess: true, cleanWhenUnstable: true, cleanWhenAborted: true)
    }
  }
}
