
%This is a modified version of the automated plot generation scripts done
%by Brian Griffin.
%The modifications were done by Brandon Nielsen with the intent of making
%it possible to generate plots of two sets of data on demand without using
%Messner.

function compare_plots_cases_driver( HOC_sim1, HOC_sim2, compare_LES, compare_best, compare_HOC, ...
					plot_arm_sim1, plot_atex_sim1, plot_bomex_sim1, plot_cobra_sim1, ...
					plot_dycoms2_rf01_sim1, plot_dycoms2_rf02_do_sim1, ...
					plot_dycoms2_rf02_ds_sim1, plot_dycoms2_rf02_nd_sim1, ...
					plot_dycoms2_rf02_so_sim1, plot_fire_sim1, plot_gabls2_sim1, ...
					plot_jun25_altocu_sim1, plot_mpace_a_sim1, plot_mpace_b_sim1, ...
                                        plot_nov11_altocu_sim1, plot_rico_sim1, plot_wangara_sim1 , ...
					plot_arm_sim2, plot_atex_sim2, plot_bomex_sim2, plot_cobra_sim2, ...
					plot_dycoms2_rf01_sim2, plot_dycoms2_rf02_do_sim2, ...
					plot_dycoms2_rf02_ds_sim2, plot_dycoms2_rf02_nd_sim2, ...
					plot_dycoms2_rf02_so_sim2, plot_fire_sim2, plot_gabls2_sim2, ...
					plot_jun25_altocu_sim2, plot_mpace_a_sim2, plot_mpace_b_sim2, ...
                                        plot_nov11_altocu_sim2, plot_rico_sim2, plot_wangara_sim2 )

%The data1 and data2 variables represent the directories that the two sets
%of data being compared
%The cmp_all variable determines whether the data being passed in will be
%compared to the data Chris_Golaz_best_ever, HOC_20051217, and LES_files

% ################# TO-DO #################
% Make it possible to turn plots on and off
% Fix how cmp_all works, even in test trim it is worthless junk (ex. does not work when 0) (Fixed July 31, 2007)
% Ensure names are meteorologist friendly

% Function call variable description:
%
% 1st entry:   Case name.
% 2nd entry:   First time of variable comparison (in minutes since the
%              beginning of the run).
% 3rd entry:   Last time of variable comparison (in minutes since the
%              beginning of the run).
% 4th entry:   The height of the bottom of the output graphs for each case.
% 5th entry:   The height of the top of the output graphs for each case.
% 6th entry:   The directory path that contains the LES files for
%              comparison. (omit the '/' at the very end.)
% 7th entry:   The directory path that contains the HOC "Chris Golaz
%              'best-ever'" files for comparison. (omit the '/' at the very
%              end.)
% 8th entry:   The directory path that contains the HOC December 17, 2005
%              files for comparison. (omit the '/' at the very end.)
% 9th entry:   The directory path that contains the HOC previous files
%              (from the prior CVS commitment) for comparison. (omit the
%              '/' at the very end.)
% 10th entry:  The directory path that contains the HOC current files (from 
%              the latest CVS commitment) for comparison. (omit the '/' at
%              the very end.)
% 11th entry:  LES file for comparison:  1 = true; 0 = false.
% 12th entry:  LES being using for comparison (supports coamps and rams).
% 13th entry:  Chris Golaz "best-ever" HOC file for comparison:  1 = true;
%                                                                0 = false.
% 14th entry:  December 17, 2005 HOC file for comparison:  1 = true;
%                                                         0 = false.
% 15th entry:  Previous CVS HOC file for comparison:  1 = true; 
%                                                    0 = false.
% 16th entry:  Current HOC file for comparison:  1 = true; 0 = false.

%Lets test some things
%Script runs when variables are explicitly defined (obviously...)
%'Hard assigning variables:'
%HOC_sim1 = 'HOC_current'
%HOC_sim2 = 'HOC_previous'
%compare_all = 0

%Determine if HOC_sim2 exists (should be plotted)
compare_sim2 = 1

if HOC_sim2 == 0
	compare_sim2 = 0
end;	

%Display the variables to potentially see what is wrong
'Variables set as follows:'
HOC_sim1
HOC_sim2
compare_sim2
compare_LES
compare_best
compare_HOC

if plot_arm_sim1 == 1
	if plot_arm_sim2 == 0
         	compare_plots_cases( 'arm', 481, 540, 0.0, 3500.0, ...
                              'LES_files', 'Chris_Golaz_best_ever', ...
                              'HOC_20051217', HOC_sim1, HOC_sim2, ...
                              compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
			      0 );
	elseif plot_arm_sim2 == 1
         	compare_plots_cases( 'arm', 481, 540, 0.0, 3500.0, ...
                              'LES_files', 'Chris_Golaz_best_ever', ...
                              'HOC_20051217', HOC_sim1, HOC_sim2, ...
                              compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
			      compare_sim2 );		
	end;
elseif plot_arm_sim1 == 0
	if plot_arm_sim2 == 0
         	'No sim data available for Arm, not plotting Arm.';
	elseif plot_arm_sim2 == 1
         	compare_plots_cases( 'arm', 481, 540, 0.0, 3500.0, ...
                              'LES_files', 'Chris_Golaz_best_ever', ...
                              'HOC_20051217', HOC_sim1, HOC_sim2, ...
                              compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
			      compare_sim2 );		
	end;
end;

if plot_atex_sim1 == 1
	if plot_atex_sim2 == 0
         	compare_plots_cases( 'atex', 421, 480, 0.0, 2500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_atex_sim2 == 1
         	compare_plots_cases( 'atex', 421, 480, 0.0, 2500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_atex_sim1 == 0
	if plot_atex_sim2 == 0
         	'No sim data available for Atex, not plotting Atex.';
	elseif plot_atex_sim2 == 1
         	compare_plots_cases( 'atex', 421, 480, 0.0, 2500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;

end;

if plot_bomex_sim1 == 1
	if plot_bomex_sim2 == 0
         	compare_plots_cases( 'bomex', 181, 360, 0.0, 2500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_bomex_sim2 == 1
         	compare_plots_cases( 'bomex', 181, 360, 0.0, 2500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_bomex_sim1 == 0
	if plot_bomex_sim2 == 0
         	'No sim data available for Bomex, not plotting Bomex.';
	elseif plot_bomex_sim2 == 1
         	compare_plots_cases( 'bomex', 181, 360, 0.0, 2500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;

end;

if plot_cobra_sim1 == 1
	if plot_cobra_sim2 == 0
         	compare_plots_cases( 'cobra', 241, 300, 0.0, 3500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', 0, 0, 1, ...
					0 );
	elseif plot_cobra_sim2 == 1
         	compare_plots_cases( 'cobra', 241, 300, 0.0, 3500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_cobra_sim1 == 0
	if plot_cobra_sim2 == 0
         	'No sim data available for Cobra, no plotting Cobra.';
	elseif plot_cobra_sim2 == 1
         	compare_plots_cases( 'cobra', 241, 300, 0.0, 3500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_dycoms2_rf01_sim1 == 1
	if plot_dycoms2_rf01_sim2 == 0
         	compare_plots_cases( 'dycoms2_rf01', 181, 240, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_dycoms2_rf01_sim2 == 1
         	compare_plots_cases( 'dycoms2_rf01', 181, 240, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_dycoms2_rf01_sim1 == 0
	if plot_dycoms2_rf01_sim2 == 0
         	'No sim data available for Dycoms2_RF01, not plotting Dycoms2_RF01.';
	elseif plot_dycoms2_rf01_sim2 == 1
         	compare_plots_cases( 'dycoms2_rf01', 181, 240, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

if plot_dycoms2_rf02_do_sim1 == 1
	if plot_dycoms2_rf02_do_sim2 == 0
        	 compare_plots_cases( 'dycoms2_rf02_do', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );

	elseif plot_dycoms2_rf02_do_sim2
        	 compare_plots_cases( 'dycoms2_rf02_do', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_dycoms2_rf02_do_sim1 == 0
	if plot_dycoms2_rf02_do_sim2 == 0
        	 'No sim data available for Dycoms2_RF02_DO, not plotting Dycons2_RF02_DO.';
	else plot_dycoms2_rf02_do_sim2 == 1
        	 compare_plots_cases( 'dycoms2_rf02_do', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

if plot_dycoms2_rf02_ds_sim1 == 1
	if plot_dycoms2_rf02_ds_sim2 == 0
         	compare_plots_cases( 'dycoms2_rf02_ds', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_dycoms2_rf02_ds_sim2 == 1
         	compare_plots_cases( 'dycoms2_rf02_ds', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_dycoms2_rf02_ds_sim1 == 0
	if plot_dycoms2_rf02_ds_sim2 == 0
         	'No sim data available for Dycoms_RF02_DS, not plotting Dycoms_RF02_DS.';
	elseif plot_dycoms2_rf02_ds_sim2 == 1
         	compare_plots_cases( 'dycoms2_rf02_ds', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

if plot_dycoms2_rf02_nd_sim1 == 1
	if plot_dycoms2_rf02_nd_sim2 == 0
         	compare_plots_cases( 'dycoms2_rf02_nd', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_dycoms2_rf02_nd_sim2 == 1
         	compare_plots_cases( 'dycoms2_rf02_nd', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_dycoms2_rf02_nd_sim1 == 0
	if plot_dycoms2_rf02_nd_sim2 == 0
         	'No sim data available for Dycoms2_RF02_ND, not plotting Dycoms2_RF02_ND.';
	elseif plot_dycoms2_rf02_nd_sim2 == 1
         	compare_plots_cases( 'dycoms2_rf02_nd', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;

end;

if plot_dycoms2_rf02_so_sim1 == 1
	if plot_dycoms2_rf02_so_sim2 == 0
        	 compare_plots_cases( 'dycoms2_rf02_so', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_dycoms2_rf02_so_sim2 == 1
        	 compare_plots_cases( 'dycoms2_rf02_so', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_dycoms2_rf02_so_sim1 == 0
	if plot_dycoms2_rf02_so_sim2 == 0
        	 'No sim data available for Dycoms_RF02_SO, not plotting Dycoms_RF02_SO.';
	elseif plot_dycoms2_rf02_so_sim2 == 1
        	 compare_plots_cases( 'dycoms2_rf02_so', 301, 360, 0.0, 1200.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

if plot_fire_sim1 == 1
	if plot_fire_sim2 == 0
        	 compare_plots_cases( 'fire', 61, 120, 0.0, 1000.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_fire_sim2 == 1
        	 compare_plots_cases( 'fire', 61, 120, 0.0, 1000.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_fire_sim1 == 0
	if plot_fire_sim2 == 0
        	 'No sim data available for Fire, not plotting Fire.';
	elseif plot_fire_sim2 == 1
        	 compare_plots_cases( 'fire', 61, 120, 0.0, 1000.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

if plot_gabls2_sim1 == 1
	if plot_gabls2_sim2 == 0
         	compare_plots_cases( 'gabls2', 2101, 2160, 0.0, 2500.0, ...
			'LES_files', 'Chris_Golaz_best_ever', ...
			'HOC_20051217', HOC_sim1, HOC_sim2, ...
			compare_LES, 'coamps', 0, 0, 1, ...
			0 );
	elseif plot_gabls2_sim2 == 1
         	compare_plots_cases( 'gabls2', 2101, 2160, 0.0, 2500.0, ...
			'LES_files', 'Chris_Golaz_best_ever', ...
			'HOC_20051217', HOC_sim1, HOC_sim2, ...
			compare_LES, 'coamps', 0, 0, 1, ...
			compare_sim2 );
	end;
elseif plot_gabls2_sim1 == 0
	if plot_gabls2_sim2 == 0
         	'No sim data available for Gabls2, not plotting Gabls2.';
	elseif plot_gabls2_sim2 == 1
         	compare_plots_cases( 'gabls2', 2101, 2160, 0.0, 2500.0, ...
			'LES_files', 'Chris_Golaz_best_ever', ...
			'HOC_20051217', HOC_sim1, HOC_sim2, ...
			compare_LES, 'coamps', 0, 0, 0, ...
			compare_sim2 );
	end;
end;

if plot_jun25_altocu_sim1 == 1
	if plot_jun25_altocu_sim2 == 0
         	compare_plots_cases( 'jun25_altocu', 61, 120, 4808.0, 7308.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_jun25_altocu_sim2 == 1
         	compare_plots_cases( 'jun25_altocu', 61, 120, 4808.0, 7308.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_jun25_altocu_sim2 == 0
	if plot_jun25_altocu_sim2 == 0
         	'No sim data available for Jun25_altocu, not plotting Jun25_altocu.';
	elseif plot_jun25_altocu_sim2 == 1
         	compare_plots_cases( 'jun25_altocu', 61, 120, 4808.0, 7308.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_mpace_a_sim1 == 1
	if  plot_mpace_a_sim2 == 0
        	 compare_plots_cases( 'mpace_a', 4140, 4320, 0.0, 10000.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', 0, 0, 1, ...
					0 );
	elseif plot_mpace_a_sim2 == 1
        	 compare_plots_cases( 'mpace_a', 4140, 4320, 0.0, 10000.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_mpace_a_sim1 == 0
	if  plot_mpace_a_sim2 == 0
        	 'No sim data available for Mpace_a, not plotting Mpace_a';
	elseif plot_mpace_a_sim2 == 1
        	 compare_plots_cases( 'mpace_a', 4140, 4320, 0.0, 10000.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					0, '', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_mpace_b_sim1 == 1
	if  plot_mpace_b_sim2 == 0
        	 compare_plots_cases( 'mpace_b', 541, 720, 0.0, 2750.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_mpace_b_sim2 == 1
        	 compare_plots_cases( 'mpace_b', 541, 720, 0.0, 2750.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_mpace_b_sim1 == 0
	if  plot_mpace_b_sim2 == 0
        	 'No sim data available for Mpace_b, not plotting Mpace_b';
	elseif plot_mpace_b_sim2 == 1
        	 compare_plots_cases( 'mpace_b', 541, 720, 0.0, 2750.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_nov11_altocu_sim1 == 1
	if plot_nov11_altocu_sim2 == 0
         	compare_plots_cases( 'nov11_altocu', 61, 120, 4150.0, 6150.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_nov11_altocu_sim2 == 1
         	compare_plots_cases( 'nov11_altocu', 61, 120, 4150.0, 6150.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_nov11_altocu_sim1 == 0
	if plot_nov11_altocu_sim2 == 0
         	'No sim data available for Nov11_Altocu, not plotting Nov11_Altocu.';
	elseif plot_nov11_altocu_sim2 == 1
         	compare_plots_cases( 'nov11_altocu', 61, 120, 4150.0, 6150.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

if plot_rico_sim1 == 1
	if plot_rico_sim2 == 0
        	 compare_plots_cases( 'rico', 1261, 1440, 0.0, 3500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					0 );
	elseif plot_rico_sim2 == 1
        	 compare_plots_cases( 'rico', 1261, 1440, 0.0, 3500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 1, ...
					compare_sim2 );
	end;
elseif plot_rico_sim1 == 0
	if plot_rico_sim2 == 0
        	 'No sim data available for Rico, not plotting Rico.';
	elseif plot_rico_sim2 == 1
        	 compare_plots_cases( 'rico', 1261, 1440, 0.0, 3500.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'coamps', 0, 0, 0, ...
					compare_sim2 );
	end;
end;

if plot_wangara_sim1 == 1
	if plot_wangara_sim2 == 0
         	compare_plots_cases( 'wangara', 181, 240, 0.0, 1900.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'rams', compare_best, compare_HOC, 1, ...
					0 );
	elseif plot_wangara_sim2 == 1
         	compare_plots_cases( 'wangara', 181, 240, 0.0, 1900.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'rams', compare_best, compare_HOC, 1, ...
					compare_sim2 );
	end;
elseif plot_wangara_sim1 == 0
	if plot_wangara_sim2 == 0
         	'No sim data available for Wangara, not plotting Wangara.';
	elseif plot_wangara_sim2 == 1
         	compare_plots_cases( 'wangara', 181, 240, 0.0, 1900.0, ...
					'LES_files', 'Chris_Golaz_best_ever', ...
					'HOC_20051217', HOC_sim1, HOC_sim2, ...
					compare_LES, 'rams', compare_best, compare_HOC, 0, ...
					compare_sim2 );
	end;
end;

'Plot generation complete!'
