#!/usr/bin/bash

# Loop script for updating all plots generated by plotgen_main.py
# Define loop entries
ncases=6
# Comparison plots have to be treated separately as they require additional input
varopts=(1 3 4 5 7)
compinput=("y" "n")

# Loop over variable cases
for vars in ${varopts[@]}
do
  # Loop over setup cases
  for ((case=1;case<=6;case++))
  do
    echo "vars = $vars, case=$case"
    python plotgen_main.py <<< "$vars
    $case"
  done
done

# Generate comparison plots
# Loop over setup cases
vars=6
for ((case=1;case<=6;case++))
do
echo "vars = $vars, case=$case"
python plotgen_main.py <<< "$vars
$case
y"
done