pipeline {
  agent any
  stages {
    stage('Checkout Clubb and Clubb_Release') {
      steps {
        // Compare fresh development and release checkouts using the release exclusion lists.
        sh '''
          git clone https://github.com/larson-group/clubb.git
          git clone https://github.com/larson-group/clubb_release.git
        '''
      }
    }
    stage('Diff') {
      steps {
        // We diff the 2 repos and exclude a select couple of files using lists stored in version_clubb_core.txt and version_sihls.txt
        sh 'diff --exclude=.git --exclude=version_clubb_core.txt --exclude=version_silhs.txt -r clubb clubb_release'
      }
    }
  }
  post {
    failure {
      script {
        // Only the production job sends failure mail.
        if ( "${env.JOB_NAME}" == "clubb_release_diff_test" ) {
          emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
        }
      }
    }
  }
}
