pipeline {
  agent any
  stages {
    stage('Enable Model Flag for Test') {
      steps {
        sh '''sed -i "s:l_test_grid_generalization.*:l_test_grid_generalization = .true.:g" src/CLUBB_core/model_flags.F90'''
      }
    }
    stage('Turn Off Sponge Damping in Case Setups') {
      steps {
        sh '''sed -i "s:thlm_sponge_damp_settings%l_sponge_damping.*:thlm_sponge_damp_settings%l_sponge_damping = .false.:g" input/case_setups/cgils_s6_model.in'''
        sh '''sed -i "s:rtm_sponge_damp_settings%l_sponge_damping.*:rtm_sponge_damp_settings%l_sponge_damping = .false.:g" input/case_setups/cgils_s6_model.in'''
        sh '''sed -i "s:thlm_sponge_damp_settings%l_sponge_damping.*:thlm_sponge_damp_settings%l_sponge_damping = .false.:g" input/case_setups/cgils_s11_model.in'''
        sh '''sed -i "s:rtm_sponge_damp_settings%l_sponge_damping.*:rtm_sponge_damp_settings%l_sponge_damping = .false.:g" input/case_setups/cgils_s11_model.in'''
        sh '''sed -i "s:thlm_sponge_damp_settings%l_sponge_damping.*:thlm_sponge_damp_settings%l_sponge_damping = .false.:g" input/case_setups/cgils_s12_model.in'''
        sh '''sed -i "s:rtm_sponge_damp_settings%l_sponge_damping.*:rtm_sponge_damp_settings%l_sponge_damping = .false.:g" input/case_setups/cgils_s12_model.in'''
      }
    }
    stage('Compile') {
      steps {
        sh '''source /etc/profile.d/larson-group.sh
              module load gcc netcdf-fortran
              compile/compile.bash -c config/linux_x86_64_gfortran_debug.bash'''
      }
    }
    stage('Run') {
      steps {
        sh '''source /etc/profile.d/larson-group.sh
              module load gcc netcdf-fortran
              run_scripts/run_scm_all.bash'''
      }
    }
  }
  post {
    always {
      // Certain logical functions like IF statements or TRY-CATCH blocks can only operate while in a script{} block
      script {
      // This cleans out the test workspace so the next run has a fresh start
      // However this only occurs when the test is named clubb_generalized_vertical_grid_test
      // This is to prevent the branch and copy tests from deleting thier workspaces so they are available for debugging
      if ( "${env.JOB_NAME}" == "clubb_generalized_vertical_grid_test" )
      	cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenSuccess: true, cleanWhenUnstable: true)
      }
    }
    failure {
      script {
      if ( "${env.JOB_NAME}" == "clubb_generalized_vertical_grid_test" )
        // This command handles the email on failure feature of the jenkins test. This line is the same on every jenkins test.
      	emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
      }
    }
  }
}
