pipeline {
  agent any
  stages {
    stage('Run test_fatal_error_handling') {
      steps {
        sh '''
          source /etc/profile.d/larson-group.sh
          module load gcc netcdf-fortran
          python tests/test_fatal_error_handling.py
        '''
      }
    }
  }
  post {
    failure {
      script {
        // Only the production job sends failure mail.
        if ( "${env.JOB_NAME}" ==	"clubb_error_handling" ) {
          emailext(to: 'messnermet@uwm.edu', subject: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has Failed", attachLog: true, body: "${env.JOB_NAME} build ${env.BUILD_NUMBER} has failed. See the attached build log and the build results (${env.BUILD_URL}) for help troubleshooting.")
        }
      }
    }
  }
}
